# TESTS ADMINISTERED {#sec-tests}

<!-- ## Adult -->

- Comprehensive Neuropsychiatric Symptom and History Interview
- Advanced Clinical Solutions (ACS): Word Choice Test, Test of Premorbid Functioning (TOPF)
- Beck Anxiety Inventory (BAI)
- Beck Depression Inventory, 2nd ed (BDI-2)
- California Verbal Learning Test, 3rd ed (CVLT-3), Brief Form
- California Verbal Learning Test, 3rd ed (CVLT-3), Standard Form
- Comprehensive Executive Function Inventory, Parent Report (CEFI Parent)
- Comprehensive Executive Function Inventory, Self-Report (CEFI Self)
- Comprehensive Executive Function Inventory, Teacher Report (CEFI Teacher)
- Comprehensive Executive Function Inventory, Youth Report (CEFI Youth)
- Conners' Adult ADHD Diagnostic Interview for DSM-IV, Part I: History (CAADID Part 1)
- Conners' Adult ADHD Rating Scales--Observer Report: Long Version (CAARS--O:L)
- Conners' Adult ADHD Rating Scales--Self-Report: Long Version (CAARS--S:L)
- Delis-Kaplan Executive Function System (D-KEFS): Color-Word Interference Test
- Dot Counting Test (DCT)
- Neuropsychological Assessment Battery, Screener (NAB): Attention, Language, Memory, Spatial, and Executive Functions Modules
- NIH Executive Abilities--Measures and Instruments for Neurobehavioral Evaluation and Research (NIH EXAMINER): Unstructured Task, Verbal Fluency, Behavioral Rating Scale
- Personality Assessment Inventory (PAI)
- Repeatable Battery for the Assessment of Neuropsychological Status (RBANS)
- Rey-Osterrieth Complex Figure Test (ROCFT)
- Trail Making Test (TMT)
- Wechsler Adult Intelligence Scale, 4th ed (WAIS-4): Similarities, Matrix Reasoning, Letter-Number Sequencing, Coding, Symbol Search, Digit Span, Vocabulary, Information, Comprehension, Block Design, Visual Puzzles, Figure Weights, Arithmetic, Picture Completion, Cancellation, Picture Arrangement, Object Assembly
- Wechsler Individual Achievement Test, 4th ed (WIAT-4): Word Reading, Reading Comprehension, Pseudoword Decoding, Orthographic Fluency, Decoding Fluency
- Wechsler Memory Scale, 4th ed (WMS-4): Logical Memory, Verbal Paired Associates, Visual Reproduction, Visual Paired Associates, Designs, Spatial Addition, Symbol Span, Spatial Span
- Wide Range Achievement Test, 5th ed, Blue Form (WRAT-5): Word Reading
- Wide Range Achievement Test, 5th ed, Green Form (WRAT-5): Word Reading

<!-- ## Child -->

- Comprehensive Neurodevelopmental Symptom and History Interview
- Adaptive Behavior Assessment System, 3rd ed, Parent/Primary Caregiver Form (ABAS-3 Parent)
- Adaptive Behavior Assessment System, 3rd ed, Parent Form (ABAS-3 Parent)
- Adaptive Behavior Assessment System, 3rd ed, Teacher Form (ABAS-3 Teacher)
- Adaptive Behavior Assessment System, 3rd ed, Self-Report Form (ABAS-3 Self)
- Behavioral Assessment System for Children, 3rd ed, Structured Developmental History (BASC-3 SDH)
- Behavioral Assessment System for Children, 3rd ed, Parent Rating Scales, Child (BASC-3 PRS Child)
- Behavioral Assessment System for Children, 3rd ed, Parent Rating Scales, Adolescent (BASC-3 PRS Adolescent)
- Behavioral Assessment System for Children, 3rd ed, Parent Rating Scales, Preschool (BASC-3 PRS Preschool)
- Behavioral Assessment System for Children, 3rd ed, Teacher Rating Scales, Child (BASC-3 TRS Child)
- Behavioral Assessment System for Children, 3rd ed, Teacher Rating Scales, Adolescent (BASC-3 TRS Adolescent)
- Behavioral Assessment System for Children, 3rd ed, Teacher Rating Scales, Preschool (BASC-3 TRS Preschool)
- Behavioral Assessment System for Children, 3rd ed, Self-Report of Personality, Adolescent (BASC-3 SRP Adolescent)
- Behavioral Assessment System for Children, 3rd ed, Self-Report of Personality, Child (BASC-3 SRP Child)
- Bracken School Readiness Assessment, 4th ed (BSRA-4)
- Brown Executive Function/Attention Scales, Parent Report (Brown EF/A Parent)
- Brown Executive Function/Attention Scales, Teacher Report (Brown EF/A Teacher)
- Brown Executive Function/Attention Scales, Self-Report (Brown EF/A Self)
- California Verbal Learning Test, Child ed (CVLT-C)
- Childhood Autism Rating Scale, 2nd ed (CARS-2)
- Childhood Autism Rating Scale, 2nd ed, Questionnaire for Parents or Caregivers (CARS-2 QPC)
- Childhood Autism Rating Scale, 2nd ed, High-Functioning Version (CARS-2 HF)
- Children's Memory Scale, 3rd ed (CMS-3)
- Clinical Evaluation of Language Fundamentals Preschool, 3rd ed (CELF Preschool-3)
- Clinical Evaluation of Language Fundamentals, 5th ed, Ages 5-8 (CELF-5)
- Clinical Evaluation of Language Fundamentals, 5th ed, Ages 9-21 (CELF-5)
- Comprehensive Executive Function Inventory, Parent Report (CEFI Parent)
- Comprehensive Executive Function Inventory, Teacher Report (CEFI Teacher)
- Comprehensive Executive Function Inventory, Youth Report (CEFI Youth)
- Comprehensive Executive Function Inventory, Self-Report (CEFI Self)
- Conners' Rating Scale, 4th ed, Parent (Conners 4 Parent)
- Conners' Rating Scale, 4th ed, Teacher (Conners 4 Teacher)
- Conners' Rating Scale, 4th ed, Self-Report (Conners 4 Self)
- Delis-Kaplan Executive Function System (D-KEFS)
- Dot Counting Test (DCT)
- Grooved Pegboard Test
- Kaufman Test of Educational Achievement, 3rd ed, Form A (KTEA-3 Form A)
- Kaufman Test of Educational Achievement, 3rd ed, Form B (KTEA-3 Form B)
- NEPSY-II Developmental Neuropsychological Battery
- NIH Executive Abilities--Measures and Instruments for Neurobehavioral Evaluation and Research (NIH EXAMINER): Unstructured Task, Behavioral Rating Scale
- PROMIS Sleep Assessments Pediatric Parent Proxy
- Repeatable Battery for the Assessment of Neuropsychological Status (RBANS)
- Rey-Osterrieth Complex Figure Test (ROCFT)
- Trail Making Test (TMT)
- Wechsler Abbreviated Scale of Intelligence, 2nd ed (WASI-2)
- Wechsler Individual Achievement Test, 4th ed (WIAT-4): Word Reading, Reading Comprehension, Pseudoword Decoding, Orthographic Fluency, Decoding Fluency
- Wechsler Intelligence Scale for Children, 5th ed (WISC-5)
- Wechsler Preschool and Primary Scale of Intelligence, 4th ed, Ages 2-3 (WPPSI-IV)
- Wechsler Preschool and Primary Scale of Intelligence, 4th ed, Ages 4-7 (WPPSI-IV)


- Comprehensive Neurodevelopmental Symptom and History Interview
- Behavioral Assessment System for Children, 3rd ed (BASC-3): Structured Developmental History (SDH)
- Behavioral Assessment System for Children, 3rd ed (BASC-3): Parent Rating Scales (PRS)
- Behavioral Assessment System for Children, 3rd ed (BASC-3): Teacher Rating Scales (TRS)
- Behavioral Assessment System for Children, 3rd ed (BASC-3): Self-Report of Personality (SRP)
- Brown Executive Function/Attention Scales (Brown EF/A): Parent Report
- Brown Executive Function/Attention Scales (Brown EF/A): Teacher Report
- Brown Executive Function/Attention Scales (Brown EF/A): Self-Report
- Comprehensive Executive Function Inventory (CEFI): Parent-completed
- Comprehensive Executive Function Inventory (CEFI): Teacher-completed
- Comprehensive Executive Function Inventory (CEFI): Youth-completed 
- Conners 4th ed (Conners 4): Parent
- Conners 4th ed (Conners 4): Teacher
- Conners 4th ed (Conners 4): Self-Report
- PROMIS Sleep Assessments Pediatric Parent Proxy	
- Wechsler Abbreviated Scale of Intelligence, 2nd ed (WASI-2)
- Wechsler Intelligence Scale for Children, 5th ed (WISC-5)
- Kaufman Test of Educational Achievement, 3rd ed (KTEA-3)
- NEPSY-II Developmental Neuropsychological Battery
- Repeatable Battery for the Assessment of Neuropsychological Status (RBANS)
- NIH Executive Abilities--Measures and Instruments for Neurobehavioral Evaluation and Research (NIH EXAMINER): Unstructured Task, Behavioral Rating Scale
- California Verbal Learning Test, Child ed (CVLT-C)
- Rey-Osterrieth Complex Figure Test (ROCFT)
- Trail Making Test (TMT)
- Grooved Pegboard Test
- Delis-Kaplan Executive Function System (D-KEFS): Color-Word Interference Test
- CELF Preschool-3
- CELF-5 Ages 5-8
- CELF-5 Ages 9-21
- Dot Counting Test (DCT)
- Wechsler Individual Achievement Test, 4th ed (WIAT-4): Word Reading, Reading
Comprehension, Pseudoword Decoding, Orthographic Fluency, Decoding Fluency
- Wechsler Preschool and Primary Scale of Intelligence, 4th ed (WPPSI-IV, Ages 4-7):
- Wechsler Preschool and Primary Scale of Intelligence, 4th ed (WPPSI-IV, Ages 2-3):
  - Receptive Vocabulary
  - Information
  - Picture Naming
  - Block Design
  - Object Assembly
  - Picture Memory
  - Zoo Locations
- Bracken School Readiness Assessment, 4th ed (BSRA-4)
