---
title-meta: Neurobehavioral Status Exam
format:
  neurotyp-typst:
    keep-typ: true
---

```{r}
#| label: import-nse-txt
#| eval: false
#| include: false

# Construct file path
patient <- "Biggie"
scale <- "NeuropsychEval-NSE-"
ext <- ".txt"
result <- ""
file <- file.path(paste0(scale, patient, ext))

# Check all this
TODO:
start_pattern <- "Biggie"
end_pattern <- "FirstName LastName"
output_path <- file.path(here::here(patient, file))
txt <- bwu::extract_text(patient, file_path, start_pattern, end_pattern)
bwu::save_as_markdown(text = txt, output_path)
```

## Referral

`r params$patient` was referred for neuropsychological testing as part of a comprehensive
work-up for attention-deficit/hyperactivity disorder (ADHD). The results and
recommendations were discussed with `r params$first_name` during the feedback
visit on the final day of the evaluation and will be used in academic and treatment
planning.

## Background

The following information was obtained during an interview with `r params$patient` and from
review of available medical records. `r params$patient` has been experiencing symptoms of
procrastination, distractibility, and difficulty with organization and time.
She has been experiencing these symptoms since childhood, but they have been
more problematic in the past few years. She has been able to compensate for her
difficulties by working harder and longer than her peers.

Cognitive complaints: sustained attention, working memory, and organization.

## Medical History

### Past Neuropsychological Test Results

Patient denied having prior testing.

### Developmental History

- No birth complications.
- Developmental milestones: Normal.

### Medical History

-   Frequent sinus infections.
-   Other medications: vitamins, folic acid.
-   Appetite/weight: Normal, no changes.
-   Sleep: Normal, no changes.
-   Alcohol/tobacco: No history of abuse; denied current use.

### Surgical History

Patient denied.

### Psychiatric History

Patient denied.

### Family History

Patient denied a family history of neurological conditions. Her brother was
diagnosed with ADHD.

### Cultural/Social Background

`r params$patient` is a Caucasian female who was born and raised in XXXX. She is single,
never married, and has no children.

### Educational History

`r params$patient` graduated from college and completed some Master's-level courses. She
did not endorse any difficulties with advancing through school.

### Occupational History

`r params$patient` has worked full time as an administrator in a small company. She has
maintained this job for the past 6 years.

## Diagnostic Considerations

- 314.01 (F90.2) Attention-Deficit/Hyperactivity Disorder (ADHD), Combined
  Presentation
- [DSM-5/ICD-10 Codes](03.01_dsm5_icd10_dx.md)
