# NEUROBEHAVIORAL STATUS EXAM {#sec-nse}

```{r}
#| label: import-nse-txt
#| eval: false
#| include: false
patient <- "Biggie"
scale <- "NeuropsychEval-NSE-"
ext <- ".txt"
file_path <- function(patient, scale, ext) {
  result <- ""
  file <- file.path(paste0(scale, patient, ext))
  return(file)
}
file_path <- here::here(patient, "NeuropsychEval_NSE_Biggie.txt")
start_pattern <- "Biggie"
end_pattern <- "Joey"
output_path <- "~/neuropsychology/Biggie/nse_extracted_text.md"
txt <- bwu::extract_text(patient, file_path, start_pattern, end_pattern)
bwu::save_as_markdown(text = txt, output_path)
```

## Reason for Referral

Biggie Smalls is a YY-year-old, right-handed research assistant with 16 years of
education, including a B.A. in Hustling from the University of Brooklyn. He was referred in order to determine the nature and extent of
neurocognitive sequelae emerging from a history of
attention-deficit/hyperactivity disorder (ADHD).


The purpose of the current evaluation is XYZ. This report is based on a review of available medical records and information gathered across multiple days of evaluation. Treatment planning and plans for test accommodations were discussed with Ms. Smalls during the feedback visit on the final day of the examination.

## Background Information

The following information was obtained during an interview with `r params$patient` and from review of available medical records.
`r params$first_name` has been doing well in `r params$his_her` classes since starting law school and has never failed.
However, issues have begun to arise that `r params$he_she` has been unable to avoid, including being easily distracted, restlessness, constantly fidgeting, procrastination, and variable attention.
`r params$he_she_cap` suspects having ADHD and has always struggled with aspects of it.
`r params$first_name`'s mother tried to get `r params$his_her` evaluated and tested when `r params$he_she` was younger, but was never able to do so because `r params$his_her` school at the time did not agree that there were major concerns.
`r params$he_she_cap` has noticed increasing difficulty initiating tasks, especially when it comes to writing long research papers, and has been procrastinating more and more.
`r params$first_name` has read up on ADHD and believes `r params$he_she` may have it, but has been able to hide it from others, as `r params$he_she` has "gotten good at pretending to pay attention." `r params$he_she_cap` seeks further assessment and evaluation to identify any underlying neurocognitive factors influencing `r params$his_her` academic motivations and performance.

Cognitive complaints: sustained attention, working memory, and organization.


## Relevant History

### Past Neuropsychological Test Results

Patient denied having prior testing.

## Relevant History

### Birth/Early Development

- Normal pregnancy, birth, and delivery.
- Developmental milestones achieved on time.

### Medical History

::: {.block above="1.2em"}
- **Current**: Consequat ad est amet deserunt dolor amet cillum nisi irure sit consequat officia do..
- **Family**: Irure anim qui deserunt eu culpa aliqua ea consequat deserunt..
- **Medications**: None.
- **Appetite/Weight**: Stable with no significant changes recently.
- **Sleep**: Normal, no changes.
- **Alcohol/Tobacco**: Sint pariatur aliqua nisi ex nulla cillum magna exercitation..
- **Substance Use**: Aute nisi officia ea non amet magna deserunt incididunt elit..
- **Neurological Injury**: Voluptate magna do id veniam id laborum in qui magna sint ad cillum commodo.
- **Psychiatric**: ADHD, anxiety, and depression.
:::

### Behavioral/Emotional/Social

Laborum enim culpa excepteur non dolore ut consequat officia nisi proident.

### Educational History

Ea eiusmod eiusmod officia. Ut adipisicing magna nostrud aute in enim laboris ipsum amet. Ex est occaecat irure. Aliqua ea excepteur non ea dolore culpa commodo irure ipsum non. Ea in nisi laboris id laborum laborum reprehenderit officia in ad Lorem aliqua consectetur anim. Ex pariatur eu quis tempor. Amet veniam deserunt laborum do laborum eu ex.

Aliqua laborum consequat occaecat officia eu quis cillum culpa. Incididunt consequat occaecat non ullamco fugiat laboris tempor nulla. Magna amet nisi laboris eiusmod nostrud ut esse non eu irure esse. Enim amet mollit et ea labore nulla anim veniam eiusmod laboris irure.

Magna quis excepteur aliqua do cillum est duis incididunt pariatur voluptate voluptate ullamco do. Consequat ea sit elit deserunt mollit consectetur laborum est eiusmod. Do cupidatat ad irure officia ea in nisi irure adipisicing. Sint culpa nulla do non ullamco aliquip id occaecat anim proident. Qui laboris tempor quis ullamco esse laborum deserunt. Magna proident consequat ex reprehenderit excepteur amet et est exercitation.

### Occupational History

Mollit pariatur ut laborum nulla proident aute. Eu laboris tempor consectetur id qui eu. Exercitation sint cupidatat ipsum fugiat cupidatat nulla nostrud culpa elit reprehenderit sit Lorem minim officia. Ex exercitation voluptate enim pariatur voluptate magna commodo. Aute fugiat ad deserunt sunt qui ipsum. Culpa ea proident aliquip irure veniam ut. Tempor id minim commodo.

### Cultural/Social Context

Deserunt sint esse culpa exercitation adipisicing cupidatat cupidatat incididunt commodo magna. Minim irure non culpa dolore esse sit. Elit officia nulla consequat esse id consequat quis consequat quis voluptate veniam tempor fugiat. Ut in adipisicing nisi amet labore.
