<<PROMPT>>

## Area: social cognition and social functioning

Summarize and interpret these neuropsychological test scores related to the area denoted above. For scores that are Below Average, give a brief example of how this could impact the patient's daily functioning. Organize your summary and interpretation in order from scores that are Exceptionally High/Above Average to Exceptionally Low/Below Average to delineate relative strengths and weaknesses, respectively. Finally, recommended additional support that the patient should receive in areas in which scores fall Below Average to Exceptionally Low.

Prefix the output/results as follows: Headers (e.g., Relative Strengths,
Relative Weaknesses) should be padded with ###, and output that contains lists should be
unordered and padded with - instead of ordered.

<<EXAMPLE>>

Emotional intelligence and social cognition were examined through a combination of performance-based tests and semi-structured clinical interviews. Performance-based testing on measures to gauge aspects of social-emotional processing and social aptitude, which are important aspects of how individuals process social information about other adults, groups, and social contexts, was intact. Global social perception fell in the Average range, but {{< var his_her >}} overall score was significantly lower than predicted by {{< var his_her >}} General Ability Index. {{< var his_her_cap >}} ability to recognize and interpret the emotional state (happy, sad, angry, afraid, surprised, disgusted, and neutral) from a series of adult faces was average. Notably, {{< var he_she >}} performed a subset of these tasks better with multisensory input (e.g., both seeing and hearing the material).^[For example, {{< var he_she >}} had to first listen to an affectively laden audio recording and match the emotion of the speaker with the same emotion from several faces (including complex emotions such as sarcasm and confusion). Then {{< var he_she >}} had to listen to an additional set of statements and, using the prosody from the voice, match the implied tone of the speaker to one of various two-person interactions utilizing facial expressions and body language. If there was a mismatch between the speaker’s tone and the actual content of the statement that was spoken (e.g., when the speaker was being sarcastic), {{< var he_she >}} had to describe what the speaker actually meant.] Biggie obtained Average to Above-Average scores on these multisensory tasks requiring problem-solving skills in addition to basic social-emotional perception. Further, {{< var he_she >}} provided exceptionally precise verbal responses on these tasks, relying on cognition, not intuition.

<<START>>











