## General Cognitive Ability {#sec-iq}

{{< include _02-01_iq_text.qmd >}}

```{r}
#| label: setup-iq
#| include: false

# Filter by domain
domains <- c("General Cognitive Ability")

# Target phenotype
pheno <- "iq"

# Read the CSV file into a data frame
iq <- vroom::vroom("neurocog.csv")
```

```{r}
#| label: export-iq
#| include: false
#| eval: true

iq <- iq |>
  dplyr::filter(domain %in% domains)

# Select specific columns from the data frame
iq <- iq |>
  dplyr::select(
    test,
    test_name,
    scale,
    raw_score,
    score,
    ci_95,
    percentile,
    range,
    domain,
    subdomain,
    narrow,
    pass,
    verbal,
    timed,
    description,
    result,
    z,
    z_mean_domain,
    z_sd_domain,
    z_mean_subdomain,
    z_sd_subdomain,
    z_mean_narrow,
    z_sd_narrow,
    z_mean_pass,
    z_sd_pass,
    z_mean_verbal,
    z_sd_verbal,
    z_mean_timed,
    z_sd_timed
  )

# Write the resulting data frame to a new CSV file
# The file name is created by concatenating the 'pheno' variable and ".csv"
# NA values are replaced with an empty string in the output file
# Column names are included in the output file
# If the file already exists, it is overwritten (not appended)
readr::write_excel_csv(iq, paste0(pheno, ".csv"), na = "", col_names = TRUE, append = FALSE)
```

```{r}
#| label: data-iq
#| include: false
#| eval: true

# Read the data using the read_data function from the bwu library
# The phenotype is specified by the 'pheno' variable
data <- iq

# Define the scales of interest
scales <- c(
  "Auditory Working Memory (AWMI)",
  "Cognitive Proficiency (CPI)",
  "Crystallized Knowledge",
  "Fluid Reasoning (FRI)",
  "Fluid Reasoning",
  "Full Scale (FSIQ)",
  "Full Scale IQ (FSIQ)",
  "General Ability (GAI)",
  "General Ability",
  "General Intelligence",
  "Global Neurocognitive Index (G)",
  "NAB Attention Index",
  "NAB Executive Functions Index",
  "NAB Language Index",
  "NAB Memory Index",
  "NAB Spatial Index",
  "NAB Total Index",
  "Nonverbal (NVI)",
  "Perceptual Reasoning (PRI)",
  "Perceptual Reasoning",
  "Processing Speed (PSI)",
  "Processing Speed",
  "RBANS Total Index",
  "Test of Premorbid Functioning",
  "TOPF Standard Score",
  "Total NAB Index (T-NAB)",
  "Verbal Comprehension (VCI)",
  "Verbal Comprehension",
  "Visual Perception/Construction",
  "Visual Spatial (VSI)",
  "Vocabulary Acquisition (VAI)",
  "Word Reading",
  "Working Memory (WMI)",
  "Working Memory",
  "Attention Index (ATT)",
  "Language Index (LAN)",
  "Spatial Index (SPT)",
  "Memory Index (MEM)",
  "Executive Functions Index (EXE)"
)

# Filter the data using the filter_data function from the bwu library
# The domain is specified by the 'domains' variable
# The scale is specified by the 'scales' variable
data_iq <- bwu::filter_data(data, domain = domains, scale = scales)
```

```{r}
#| label: text-iq
#| cache: true
#| include: false

# export text
bwu::cat_neuropsych_results(data = data_iq, file = "_02-01_iq_text.qmd")
```

```{r}
#| label: qtbl-iq
#| dev: tikz
#| fig-process: pdf2png
#| include: false
#| eval: true

# Set the default engine for tikz to "xetex"
options(tikzDefaultEngine = "xetex")

# Define the scales to include
subset <- c(
  "Auditory Working Memory (AWMI)",
  "Cognitive Proficiency (CPI)",
  "Crystallized Knowledge",
  "Fluid Reasoning (FRI)",
  "Fluid Reasoning",
  "Full Scale (FSIQ)",
  "Full Scale IQ (FSIQ)",
  "General Ability (GAI)",
  "General Ability",
  "General Intelligence",
  "Global Neurocognitive Index (G)",
  "NAB Attention Index",
  "NAB Executive Functions Index",
  "NAB Language Index",
  "NAB Memory Index",
  "NAB Spatial Index",
  "NAB Total Index",
  "Nonverbal (NVI)",
  "Perceptual Reasoning (PRI)",
  "Perceptual Reasoning",
  "Processing Speed (PSI)",
  "Processing Speed",
  "RBANS Total Index",
  "Test of Premorbid Functioning",
  "TOPF Standard Score",
  "Total NAB Index (T-NAB)",
  "Verbal Comprehension (VCI)",
  "Verbal Comprehension",
  "Visual Perception/Construction",
  "Visual Spatial (VSI)",
  "Vocabulary Acquisition (VAI)",
  "Word Reading",
  "Working Memory (WMI)",
  "Working Memory",
  "Attention Index (ATT)",
  "Language Index (LAN)",
  "Spatial Index (SPT)",
  "Memory Index (MEM)",
  "Executive Functions Index (EXE)"
)

# Filter the data to subset only the specified scales
data_iq <- dplyr::filter(data_iq, scale %in% subset)

# Define the table name, vertical padding, and multiline setting
pheno <- "iq"
table_name <- "table_iq"
vertical_padding <- 0
multiline <- TRUE

# footnotes
fn_standard_score <- gt::md("Standard score: Mean = 100 [50th‰], SD ± 15 [16th‰, 84th‰]")

source_note <- gt::md("Standard score: Mean = 100 [50th‰], SD ± 15 [16th‰, 84th‰]")

# Define the groups for the table
grp_iq <- list(
  standard_score = c(
    "Composite Scores", "Test of Premorbid Functioning", "WAIS-IV", "WAIS-4",
    "WASI-2", "WISC-5", "WISC-V", "WRAT-5", "KTEA-3", "NAB", "NAB-S", "RBANS", "WPPSI-IV"
  )
)

# Create the table using the tbl_gt function from the bwu library
bwu::tbl_gt(
  data = data_iq,
  pheno = pheno,
  table_name = table_name,
  vertical_padding = vertical_padding,
  source_note = source_note,
  # fn_standard_score = fn_standard_score,
  # grp_standard_score = grp_iq[["standard_score"]],
  dynamic_grp = grp_iq,
  multiline = multiline
)
```

```{r}
#| label: fig-iq
#| include: false
#| fig-cap: "_Premorbid Ability_ is an estimate of an individual's intellectual functioning prior to known or suspected onset of brain disease or dysfunction. _General Ability_ is the overall skill to reason, solve problems, and gain useful knowledge. _Crystallized Knowledge_ involves understanding the world through language and reasoning. _Fluid Reasoning_ is the logical analysis and solution of new problems, identifying underlying patterns, and applying logic."

# Define the x and y variables for the dotplot
# x <- data_iq$z
# y <- data_iq$scale

# x <- data_iq$z_mean_subdomain
# y <- data_iq$subdomain

x <- data_iq$z_mean_narrow
y <- data_iq$narrow

# plot args
colors <- NULL
return_plot <- TRUE

# Define the filename for the plot
filename <- "fig_iq.svg"

# Define the scales to keep
# keep <- c("General Ability", "Crystallized Knowledge", "Fluid Reasoning")
# data_iq <- dplyr::filter(data_iq, scale %in% keep)

# Suppress warnings from being converted to errors
options(warn = 1) # Set warn to 1 to make warnings not halt execution

# Create the dotplot using the dotplot function from the bwu library
bwu::dotplot(
  data = data_iq,
  x = x,
  y = y,
  colors = colors,
  return_plot = return_plot,
  filename = filename,
  na.rm = TRUE
)

# Reset warning options to default if needed
options(warn = 0) # Reset to default behavior
```

```{=typst}
// Define a function to create a domain with a title, a table, and a figure
#let domain(title: none, file_qtbl, file_fig) = {
  let font = (font: "Roboto Slab", size: 0.5em)
  set text(..font)
  pad(top: 0.5em)[]
  grid(
    columns: (50%, 50%),
    gutter: 8pt,
    figure(
      [#image(file_qtbl)],
      caption: figure.caption(position: top, [#title]),
      kind: "qtbl",
      supplement: [*Table*],
    ),
    figure(
      [#image(file_fig, width: auto)],
      caption: figure.caption(
        position: bottom,
        [
        The Neurocognitive Index evaluates cognitive functioning across five domains: Attention (focus, concentration, and information processing), Language (verbal communication, naming, comprehension, and fluency), Memory (immediate and delayed verbal and visual recall), Spatial (visuospatial perception, construction, and orientation), and Executive Functions (planning, problem-solving, and mental flexibility). #footnote[In the figures presented here and below, scores have been converted to _z_-scores, where an average score is 0.0 and the standard deviation is 1.0. Any scores below the −1.0 ticks are moderately concerning. Scores at or beyond the −2.0 ticks are clinically significant and a cause for greater concern.]
        ],
      ),
      placement: none,
      kind: "image",
      supplement: [*Figure*],
      gap: 0.5em,
    ),
  )
}
```

```{=typst}
// Define the title of the domain
#let title = "General Cognitive Ability"

// Define the file name of the table
#let file_qtbl = "table_iq.png"

// Define the file name of the figure
#let file_fig = "fig_iq.svg"

// The title is appended with ' Index Scores'
#domain(title: [#title Scores], file_qtbl, file_fig)
```
