## ADHD/Executive Function {#sec-adhd}

{{< include _02-09_adhd_text.qmd >}}

```{r}
#| label: data-adhd
#| eval: false
#| include: false

library(tidyverse)
library(gt)
library(gtExtras)
library(glue)
library(bwu)

pheno <- "adhd"
df <- readr::read_csv("read_data_scales.csv")
domains <- df$domains
string_representation <- df$scales

# Extract the inner part of the string to get the content inside c(...)
inner_string <- gsub("^.+\"c\\((.*)\\)\"$", "\\1", string_representation)

# Use eval and parse to convert the string into an actual R object
scales <- eval(parse(text = paste("c(", inner_string, ")", sep = "")))

data <- bwu::read_data(pheno = pheno)

data_adhd <-
  bwu::filter_data(data,
    domain = domains,
    scale = scales
  )
```

```{r}
#| label: data-adhd2
#| include: false

library(tidyverse)
library(gt)
library(gtExtras)
library(glue)
library(bwu)
data <- bwu::read_data(pheno = "adhd")
domains <- c("ADHD")
scales <- c(
  "Activation",
  "Focus",
  "Effort",
  "Emotion",
  "Memory",
  "Action",
  "Total Composite",
  "CAARS-SR Inattention/Memory Problems", "CAARS-SR Hyperactivity/Restlessness",
  "CAARS-SR Impulsivity/Emotional Lability", "CAARS-SR Problems with
  Self-Concept", "CAARS-SR DSM-5 Inattentive Symptoms", "CAARS-SR DSM-5
  Hyperactive-Impulsive Symptoms", "CAARS-SR DSM-5 ADHD Symptoms Total",
  "CAARS-SR ADHD Index", "CEFI-SR Full Scale", "CEFI-SR Attention", "CEFI-SR
  Emotion Regulation", "CEFI-SR Flexibility", "CEFI-SR Inhibitory Control",
  "CEFI-SR Initiation", "CEFI-SR Organization", "CEFI-SR Planning", "CEFI-SR
  Self-Monitoring", "CEFI-SR Working Memory", "CAARS-OR Inattention/Memory
  Problems", "CAARS-OR Hyperactivity/Restlessness", "CAARS-OR
  Impulsivity/Emotional Lability", "CAARS-OR Problems with Self-Concept",
  "CAARS-OR DSM-5 Inattentive Symptoms", "CAARS-OR DSM-5 Hyperactive-Impulsive
  Symptoms", "CAARS-OR DSM-5 ADHD Symptoms Total", "CAARS-OR ADHD Index",
  "CEFI-OR Full Scale", "CEFI-OR Attention", "CEFI-OR Emotion Regulation",
  "CEFI-OR Flexibility", "CEFI-OR Inhibitory Control", "CEFI-OR Initiation",
  "CEFI-OR Organization", "CEFI-OR Planning", "CEFI-OR Self-Monitoring",
  "CEFI-OR Working Memory"
)

data_adhd <- bwu::filter_data(data, domain = domains, scale = scales)
```


```{r}
#| label: text-adhd-self
#| cache: true
#| eval: false
#| include: false

# Self-report
data_sr <-
  data_adhd |>
  dplyr::filter(test == "cefi_sr" | test == "caars_sr") |>
  dplyr::arrange(dplyr::desc(percentile)) |>
  dplyr::distinct(.keep_all = FALSE)
# Flatten the text
bwu::cat_neuropsych_results(data = data_sr, file = "_02-09_adhd_text.qmd")
```

```{r}
#| label: text-adhd-observer
#| cache: true
#| eval: false
#| include: false

# Observer reports
data_or <-
  data |>
  dplyr::filter(test == "cefi_or" | test == "caars_or") |>
  dplyr::arrange(dplyr::desc(percentile)) |>
  dplyr::distinct(.keep_all = FALSE)

# Flatten the text
bwu::cat_neuropsych_results(data = data_or, file = "_02-09_adhd_text.qmd")
```

```{r}
#| label: text-adhd-parent
#| cache: true
#| eval: true
#| include: false

# parent reports
data_adhd_parent <-
  data_adhd |>
  dplyr::filter(test == "cefi_or" | test == "caars_or" | test == "brown_efa_parent")

# Flatten the text
bwu::cat_neuropsych_results(data = data_adhd_parent, file = "_02-09_adhd_text.qmd")
```

```{r}
#| label: text-adhd-teacher
#| cache: true
#| eval: false
#| include: false
TODO:
# Observer reports
data_or <-
  data |>
  dplyr::filter(test == "cefi_or" | test == "caars_or" | test == "brown_efa_parent") |>
  dplyr::arrange(dplyr::desc(percentile)) |>
  dplyr::distinct(.keep_all = FALSE)

# Flatten the text
bwu::cat_neuropsych_results(data = data_or, file = "_02-09_adhd_text.qmd")
```

```{r}
#| label: qtbl-adhd-sr
#| dev: tikz
#| fig-process: pdf2png
#| eval: false
#| include: false
options(tikzDefaultEngine = "xetex")

grp_adhd <- list(
  standard_score = c("CEFI Self-Report", "CEFI Observer-Report"),
  t_score = c("CAARS Self-Report", "CAARS Observer-Report")
)
grp_caars <- list(
  t_score = c("CAARS Self-Report", "CAARS Observer-Report")
)
grp_cefi <- list(
  standard_score = c("CEFI Self-Report", "CEFI Observer-Report")
)
# footnotes
fn_standard_score <- gt::md("CEFI: Standard Score: Mean = 100 [50th‰], SD ± 15 [16th‰, 84th‰], lower scores reflect reduced functioning.")
fn_t_score <- gt::md("CAARS: *T*-Score: Mean = 50 [50th‰], SD ± 10 [16th‰, 84th‰]; higher scores reflect reduced functioning.")
# variables
data <- data_sr
pheno <- "self_report"
table_name <- "table_sr"
vertical_padding <- 0
multiline <- TRUE
fn_standard_score <- fn_standard_score
fn_t_score <- fn_t_score
grp_sr <- list(
  standard_score = c("CEFI Self-Report"),
  t_score = c("CAARS Self-Report")
)

# Self-Report
bwu::tbl_gt(
  data = data,
  pheno = pheno,
  table_name = table_name,
  fn_standard_score = fn_standard_score,
  fn_t_score = fn_t_score,
  grp_standard_score = grp_sr[["standard_score"]],
  grp_t_score = grp_sr[["t_score"]],
  dynamic_grp = grp_sr,
  vertical_padding = vertical_padding,
  multiline = multiline
)
```

```{r}
#| label: qtbl-adhd-or
#| dev: tikz
#| fig-process: pdf2png
#| eval: false
#| include: false
options(tikzDefaultEngine = "xetex")

# footnotes
fn_standard_score <- gt::md("CEFI Standard Score: Mean = 100 [50th‰], SD ± 15 [16th‰, 84th‰]; lower scores reflect reduced functioning.")
fn_t_score <- gt::md("CAARS *T*-Score: Mean = 50 [50th‰], SD ± 10 [16th‰, 84th‰]; higher scores reflect reduced functioning.")

# Observer-Report
data <- data_or
pheno <- "observer_report"
table_name <- "table_or"
vertical_padding <- 0
multiline <- TRUE
fn_standard_score <- fn_standard_score
fn_t_score <- fn_t_score
grp_or <- list(
  standard_score = c("CEFI Observer-Report"),
  t_score = c("CAARS Observer-Report")
)

# Observer-Report
bwu::tbl_gt(
  data = data,
  pheno = pheno,
  table_name = table_name,
  fn_standard_score = fn_standard_score,
  fn_t_score = fn_t_score,
  grp_standard_score = grp_or[["standard_score"]],
  grp_t_score = grp_or[["t_score"]],
  dynamic_grp = grp_or,
  vertical_padding = vertical_padding,
  multiline = multiline
)
```

```{r}
#| label: qtbl-adhd-parent
#| dev: tikz
#| fig-process: pdf2png
#| eval: true
#| include: false
options(tikzDefaultEngine = "xetex")

# footnotes
source_note <- gt::md("Brown EF/A Scale *T* Scores: Mean = 50 [50th‰], SD ± 10
[16th‰, 84th‰]; Low to average scores are typical on this measure, and high scores reflect difficulties in executive functioning.")

# fn_t_score <- gt::md("Brown EF/A Scales: *T* Score: Mean = 50 [50th‰], SD ± 10
# [16th‰, 84th‰]; higher scores reflect difficulties in executive functioning.")

# parent report
# data <- dplyr::arrange(data_or, absort)
pheno <- "adhd_parent"
table_name <- "table_adhd_parent"
grp_adhd_parent <- list(t_score = c("Brown EF/A Parent Ratings"))
vertical_padding <- 0
multiline <- TRUE

bwu::tbl_gt(
  data = data_adhd_parent,
  pheno = pheno,
  table_name = table_name,
  source_note = source_note,
  # fn_t_score = fn_t_score,
  grp_t_score = grp_adhd_parent[["t_score"]],
  dynamic_grp = grp_adhd_parent,
  vertical_padding = vertical_padding,
  multiline = multiline
)
```


```{r}
#| label: fig-caars
#| eval: false
#| include: false
#| fig-cap: "Attention and executive functions are multidimensional concepts that contain several related processes. Both concepts require self-regulatory skills and have some common subprocesses; therefore, it is common to treat them together, or even to refer to both processes when talking about one or the other."

# data for caars dotplot
pheno <- "caars"
data_caars <- dplyr::filter(data, filename %in% c("caars_sr.csv", "caars_or.csv"))
colors <- NULL
# return_plot <- FALSE
return_plot <- Sys.getenv("RETURN_PLOT")
filename <- "fig_caars.svg"
x <- data_caars$z_mean_subdomain
y <- data_caars$subdomain

# Make dotplot
bwu::dotplot(
  data = data_caars,
  x = x,
  y = y,
  colors = colors,
  return_plot = return_plot,
  filename = filename
)
```

```{r}
#| label: fig-cefi
#| eval: false
#| include: false
#| fig-cap: "Attention and executive functions are multidimensional concepts that contain several related processes. Both concepts require self-regulatory skills and have some common subprocesses; therefore, it is common to treat them together, or even to refer to both processes when talking about one or the other."

# data for cefi dotplot
pheno <- "cefi"
data_cefi <- dplyr::filter(data, filename %in% c("cefi_sr.csv", "cefi_or.csv"))
colors <- NULL
# return_plot <- TRUE
return_plot <- Sys.getenv("RETURN_PLOT")
filename <- "fig_cefi.svg"
x <- data_cefi$z_mean_narrow
y <- data_cefi$narrow

# Make dotplot
bwu::dotplot(
  data = data_cefi,
  x = x,
  y = y,
  colors = colors,
  return_plot = return_plot,
  filename = filename
)
```

```{r}
#| label: fig-adhd-parent
#| eval: true
#| include: false
#| fig-cap: "Attention and executive functions are multidimensional concepts that contain several related processes. Both concepts require self-regulatory skills and have some common subprocesses; therefore, it is common to treat them together, or even to refer to both processes when talking about one or the other."

# args
colors <- NULL
# return_plot <- TRUE
return_plot <- Sys.getenv("RETURN_PLOT")
filename <- "fig_adhd_parent.svg"
x <- data_adhd_parent$z_mean_narrow
y <- data_adhd_parent$narrow

# Make dotplot
bwu::dotplot(
  data = data_adhd_parent,
  x = x,
  y = y,
  colors = NULL,
  return_plot = return_plot,
  filename = filename
)
```


```{=typst}
#let domain(title: none, file_qtbl, file_fig) = {
  let font = (font: "Fira Sans", size: 9pt)
  set text(..font)
    grid(
      columns: (50%, 50%),
      rows: (50%, 50%),
      gutter: 8pt,
        figure([#image(file_qtbl)],
          caption: figure.caption(position: top, [#title]),
          kind: "qtbl",
          supplement: [*Table*],
          ),
        figure([#image(file_fig)],
          caption: figure.caption(position: bottom, [
            Attention and executive functions are multidimensional concepts that contain several related processes. Both concepts require self-regulatory skills and have some common subprocesses; therefore, it is common to treat them together, or even to refer to both processes when talking about one or the other.
            ]),
          placement: none,
          kind: "image",
          supplement: [*Fig.*],
          gap: 0.5em,
        ),
      )
  }
```

```{=typst}
#let title = "Parent Ratings of ADHD-Related Executive Function"
#let file_qtbl = "table_adhd_parent.png"
#let file_fig = "fig_adhd_parent.svg"
#domain(
  title: [#title],
  file_qtbl,
  file_fig
)
```
