---
execute:
  cache: true
---

<!---
 # General Cognitive Ability 
--->

<<PROMPT>>

Summarize and interpret these neuropsychological test scores related to
intellectual and neuropsychological functioning. For scores that are
below average, give a brief example of how this could impact the patient's daily
functioning. Organize your summary and interpretation in order from scores that
are above average to below average to delineate relative strengths and
weaknesses, respectively.

<<START>>
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
NA
An estimate of working memory capacity^[(ref:working-memory)] fell in the Exceptionally High range and was and a relative strength|weakness.
An estimate of higher cognitive reasoning and acquired knowledge (*g*) was Above Average and ranked at the 97th percentile, indicating performance as good as or better than 97% of same-age peers from the general population.
Crystallized intelligence (*G*c) was classified as Above Average and ranked at the 96th percentile.
NA
NA
An estimate of premorbid verbal ability level fell within the Above Average range.^[(ref:premorbid)]
An estimate of fluid intelligence (*G*f) was classified as High Average.
Finally, a comprehensive measure of neuropsychological functioning (independent of general intelligence) in the domains of attentional and executive functioning, language, spatial processing, and memory fell in the High Average range.
Collective performance across measures of processing speed and cognitive efficiency^[(ref:processing-speed)] was Average and a relative strength|weakness.
NA
