---
title-meta: iq
execute:
  warning: false
  echo: false
  message: false
format:
  typst:
    keep-typ: true
  pdf:
    keep-md: true
    keep-tex: true
  html: 
    toc: true
---

<!-- ### General Cognitive Ability -->

```{r}
#| label: data-g
library(readr)
library(dplyr)
library(bwu)
patient <- "~/neurocog"
g <- bwu::gpluck_get_index_scores(patient = patient)
```

```{r}
#| label: data-iq

# which csv file to use
pheno <- "iq"

if (pheno == "adhd" || pheno == "emotion") {
  csv <- "neurobehav.csv"
} else {
  csv <- "neurocog.csv"
}

# read data
file_path <- file.path(csv)
data <- readr::read_csv(file_path)
```

```{r}
#| label: filter-iq
#| cache: true

# FILTER DATA
# filter by broad domain
domain <- "Intelligence/General Ability"
data <- data |>
  dplyr::filter(domain == !!domain) |> 
  dplyr::filter(!is.na(percentile))

# filter by scale
filter_file <- c(
  ## ACS TOPF
  "Test of Premorbid Functioning",
  "TOPF Standard Score",
  ## WRAT5 Word Reading
  "Word Reading",
  ## NAB
  "NAB Total Index",
  "NAB Attention Index",
  "NAB Language Index",
  "NAB Memory Index",
  "NAB Spatial Index",
  "NAB Executive Functions Index",
  ## RBANS
  "RBANS Total Index",
  ## WISC/WAIS/WPPSI
  "Full Scale (FSIQ)",
  "General Ability (GAI)",
  "Cognitive Proficiency (CPI)",
  "Verbal Comprehension (VCI)",
  "Perceptual Reasoning (PRI)",
  "Fluid Reasoning (FRI)",
  "Visual Spatial (VSI)",
  "Vocabulary Acquisition (VAI)",
  "Nonverbal (NVI)",
  "Processing Speed (PSI)",
  "Working Memory (WMI)",
  ## composite scores
  "General Ability",
  "General Ability Index",
  "Crystallized Knowledge",
  "Crystallized Knowledge Index",
  "Fluid Reasoning",
  "Fluid Reasoning Index",
  "Cognitive Proficiency",
  "Cognitive Proficiency Index",
  "Working Memory",
  "Working Memory Index",
  "Processing Speed",
  "Processing Speed Index",
  "General Intelligence",
  "Cognitive Efficiency"
)

data <- dplyr::filter(data, scale %in% filter_file)
```

```{r}
#| label: text-iq
#| cache: true
xfun::pkg_attach(c("glue", "purrr", "dplyr", "epoxy"))

# This code sorts the data by percentile and then removes duplicate rows based on the percentile variable. The resulting data is then converted to text and appended to the _academics_raw.qmd file.
data_text <-
  data |>
  dplyr::arrange(dplyr::desc(percentile)) |>
  dplyr::distinct(.keep_all = FALSE)

data_text |>
  glue::glue_data() |>
  purrr::modify(purrr::as_mapper(~ paste0(.x))) |>
  cat(data_text$result,
    file = "_02_iq_raw.qmd",
    fill = TRUE,
    append = TRUE
  )
# subscale <- split(data_text, data_text$scale)
```

```{r}
#| label: qtbl-iq

# GT table
xfun::pkg_attach2(c("gt", "dplyr", "glue", "webshot2", "gtExtras", "bwu"))

# more filtering for tables
data <- dplyr::arrange(data, test_name, absort, .by_group = TRUE)

# source note
source_note <- gt::md("*Note:* Index scores have a mean of 100 and a standard deviation of 15.")

# run fc
table_iq <- bwu::tbl_gt(
  data,
  table_name = "table_iq",
  source_note = source_note,
  title = NULL
)
table_iq

# save
gt::gtsave(table_iq, glue("table_iq", ".png"), expand = 10)
gt::gtsave(table_iq, glue("table_iq", ".pdf"), expand = 10)
```

```{=typst}
<qtbl-iq>
#figure([#image("table_iq.png", width: 70%)],
  caption: [
    Composite intellectual and neuropsychological index scores
  ],
  kind: "qtbl",
  supplement: [Table],
)
```
```{r}
#| label: fig-iq
#| eval: true
#| fig-cap: "*General Ability* refers to an overall capacity to reason, to solve problems, and to learn useful information. *Crystallized Knowledge* refers to the ability to learn and use language to reason and understand how the world works. *Fluid Reasoning* refers to the ability to use logical reasoning to figure things out without being told exactly how things work, analyze and solve novel problems, identify patterns and relationships that underpin these problems, and apply logic."

# load packages
xfun::pkg_attach(c(
  "gt", "tidyverse", "glue", "webshot2", "ggplot2", "ggthemes",
  "scales", "bwu"
))

# more filtering for plots
data_dotplot <- dplyr::filter(
  data,
  scale %in% c("General Ability", "Crystallized Knowledge", "Fluid Reasoning")
)

# data <- dplyr::filter(data, !is.na(percentile))

# will need to change these for each domain
fig_iq <- bwu::dotplot(
  data = data_dotplot,
  x = data_dotplot$z_mean_narrow,
  y = data_dotplot$narrow,
  fill = x
)

fig_iq

ggplot2::ggsave("fig_iq.png")
ggplot2::ggsave("fig_iq.pdf")
```

```{r}
#| label: tbl-md-iq
#| eval: true
#| tbl-cap: "General Cognitive Ability"

# markdown table; change label if want to use
markdown_table_typst <- function(data) {
  data.frame(
    data
  ) |>
    kableExtra::kbl(
      format = "markdown",
      table.envir = "figure",
      longtable = FALSE,
      booktabs = TRUE,
      linesep = "",
      align = c("lccc"),
      col.names = c("**Scale**", "**Score**", "**‰ Rank**", "**Range**")
    )
}
tbl_md <- markdown_table_typst(data[, c(2, 4, 5, 6)])
tbl_md
```

```{r}
#| label: csv-iq
iq <- data[, c(2, 4, 5, 6)]
readr::write_csv(iq, "iq.csv", col_names = FALSE)
```
