# APPENDIX

## Examiner Qualifications

I possess a comprehensive and distinguished background in the field of psychopathology and forensic neuropsychology, underpinned by nearly two decades of research and clinical practice. My academic journey encompasses four psychology degrees: a B.A., M.A., M.Phil., and Ph.D., laying a solid foundation for my expertise in developmental neuropsychology and disruptive behavioral disorders. My professional training includes an APA-accredited predoctoral internship in pediatric neuropsychology at Henry Ford Hospital in Detroit, Michigan, followed by a postdoctoral fellowship in psychiatric genetics at the National Institute of Mental Health, part of the National Institutes of Health in Bethesda, Maryland. I am duly licensed as a psychologist in both California and New York.

Throughout my career, I have held several prestigious positions, including Director of the Laboratory of Cognitive Genomics at Zucker Hillside Hospital, Assistant Investigator of Psychiatric Neuroscience at the Feinstein Institute for Medical Research, and Assistant Professor of Psychiatry at the Hofstra School of Medicine at Northwell Health in Long Island, New York. Presently, I serve as an Assistant Professor in the Department of Psychiatry and Behavioral Sciences at the Keck School of Medicine of the University of Southern California. My contributions to research and clinical practice were recognized in 2019 when I was honored with the Della Martin Assistant Professor of Psychiatry endowed professorship from USC, a testament to my impact on the university and the wider scientific community.

My research endeavors have been prolific, resulting in several publications in high-impact scientific journals. These studies have focused on the trajectory of symptom stability and neuropsychological functioning from early childhood to young adulthood in individuals with ADHD, contributing valuable insights to the field [@De2008; @Miller2006; @Trampush2009; @bedardPerceptualMotorInhibition2010; @HalperinTrampush2008; @rajendranAssociationVariationNeuropsychological2013; @trampushModeratorEffectsWorking2014]. In my clinical capacity, I have conducted over 200 neurocognitive and psychodiagnostic evaluations of ADHD and related neuropsychiatric syndromes, covering a diverse range of ages, genders, ethnicities, and comorbidities. This extensive experience underscores my commitment to advancing our understanding and treatment of neuropsychological disorders.


## Test Selection Procedures

Neuropsychological tests are intrinsically performance-based, and cognitive performance assessed during this examination is summarized above.
Where appropriate, qualitative observations are included.
Cultural considerations were made when selecting measures, interpreting results, and making diagnostic impressions and recommendations.
Results from formal tests are reported in comparison to other individuals the same age and sex/gender as range of functioning (e.g., Below Average, Average, Above Average).[@guilmetteAmericanAcademyClinical2020]
Test score labels are intended solely to be descriptive, identifying positions of scores relative to a normal curve distribution, and should be interpreted within the context of the patient's individual presentation and history.
Although standardized scores provide the clinician with an important and necessary understanding of the patient's test performance compared with a normative group, they do not on their own lead to accurate diagnosis or treatment recommendations.

## Conversion of Test Scores

```{=typst}
#import "@preview/tablex:0.0.6": tablex, gridx, hlinex, vlinex, colspanx, rowspanx
#import "@preview/tablem:0.1.0": tablem

#set text(10pt)
#let three-line-table = tablem.with(
  render: (columns: auto, ..args) => {
    tablex(
      columns: (auto, 1fr, 1fr, 1fr, 1fr, 1fr),
      auto-lines: false,
      align: (col, row) =>
            if row == 0 { center + horizon }
            else if col == 0 { left + horizon }
            else { center + horizon },
      hlinex(y: 0),
      hlinex(y: 1),
      ..args,
      hlinex(),
    )
  }
)

#three-line-table[
|*Range*|*Standard Score*|*T-Score*|*Scaled Score*|*z-Score*|*Percentile (‰)*|
|---|---|---|---|---|---|
|Exceptionally high score|130 +|70 +|16 +|2 +|98 +|
|Above average score|120 – 129|63 – 69|14 – 15|1.3 – 1.9|91 – 97|
|High average score|110 – 119|57 – 62|12 – 13|0.7 – 1.2|75 – 90|
|Average score|90 – 109|44 – 56|9 – 11|-0.7 – 0.6|25 – 74|
|Low average score|80 – 89|37 – 43|7 – 8|-1.3 – -0.6|9 – 24|
|Below average score|70 – 79|30 – 36|4 – 6|-2 – -1.4|2 – 8|
|Exceptionally low score|< 70|< 30|< 4|< -2|< 2|
]
```
