---
title-meta: academics
execute:
  warning: false
  echo: false
  message: false
format:
  typst:
    keep-typ: true
  pdf:
    keep-md: true
    keep-tex: true
---

<!-- ### Academic Skills -->

```{r}
#| label: data-academics
library(readr)
library(dplyr)
library(bwu)

# which csv file to use
pheno <- "academics"

if (pheno == "adhd" || pheno == "emotion") {
  csv <- "neurobehav.csv"
} else {
  csv <- "neurocog.csv"
}

# read data
file_path <- file.path(csv)
data <- readr::read_csv(file_path)
```

```{r}
#| label: filter-academics

# FILTER DATA
# filter by broad domain
domain <- "Academic Skills"
data <- dplyr::filter(data, domain == !!domain)

# filter by scale
filter_file <- c(
  ## WRAT5
  "Word Reading",
  "Math Computation",
  "Spelling",
  "Sentence Comprehension",
  "Reading Composite",
  ## CELF-3 Preschool
  "Academic Language Readiness Index",
  ## KTEA-3
  "Academic Skills Battery (ASB) Composite",
  "Math Concepts & Applications",
  "Letter & Word Recognition",
  "Written Expression",
  "Math Computation",
  "Spelling",
  "Reading Comprehension",
  "Reading Composite",
  "Math Composite",
  "Written Language Composite",
  "Sound-Symbol Composite",
  "Phonological Processing",
  "Nonsense Word Decoding",
  "Decoding Composite",
  "Reading Fluency Composite",
  "Silent Reading Fluency",
  "Word Recognition Fluency",
  "Decoding Fluency",
  "Reading Understanding Composite",
  "Reading Vocabulary",
  "Oral Language Composite",
  "Associational Fluency",
  "Listening Comprehension",
  "Oral Expression",
  "Oral Fluency Composite",
  "Object Naming Facility",
  "Comprehension Composite",
  "Expression Composite",
  "Orthographic Processing Composite",
  "Letter Naming Facility",
  "Academic Fluency Composite",
  "Writing Fluency",
  "Math Fluency",
  ## WAIS
  # "Arithmetic"
  ## WIAT-4
  "Alphabet Writing Fluency",
  "Basic Reading",
  "Decoding Fluency",
  "Decoding",
  "Dyslexia Index",
  "Essay Composition",
  "Expressive Vocabulary",
  "Listening Comprehension",
  "Math Fluency-Addition",
  "Math Fluency-Multiplication",
  "Math Fluency-Subtraction",
  "Math Fluency",
  "Math Problem Solving",
  "Mathematics",
  "Numerical Operations",
  "Oral Discourse Comprehension",
  "Oral Expression",
  "Oral Reading Fluency",
  "Oral Word Fluency",
  "Orthographic Choice",
  "Orthographic Fluency",
  "Orthographic Processing Extended",
  "Orthographic Processing",
  "Phonemic Proficiency",
  "Phonological Processing",
  "Pseudoword Decoding",
  "Reading Comprehension",
  "Reading Fluency",
  "Reading",
  "Reading Index",
  "Receptive Vocabulary",
  "Sentence Composition",
  "Sentence Repetition",
  "Sentence Writing Fluency",
  "Spelling",
  "Total Achievement",
  "Word Reading",
  "Written Expression"
)
data <- dplyr::filter(data, scale %in% filter_file)
```

```{r}
#| label: text-academics
#| cache: true
library(glue)
library(purrr)
library(dplyr)

data_text <-
  data |>
  dplyr::arrange(dplyr::desc(percentile)) |>
  dplyr::distinct(.keep_all = FALSE)

data_text |>
  glue::glue_data() |>
  purrr::modify(purrr::as_mapper(~ paste0(.x))) |>
  cat(data_text$result,
    file = "_03_academics_raw.qmd",
    fill = TRUE,
    append = TRUE
  )
```

```{r}
#| label: qtbl-academics
#| fig-align: center
#| cache: false

# GT table
xfun::pkg_attach2(c("gt", "dplyr", "glue", "webshot2", "gtExtras", "bwu"))

# more filtering for tables
data <- dplyr::arrange(data, test_name)

# source note
source_note <- gt::md("*Note:* Index scores have a mean of 100 and a standard deviation of 15.")

# run fc
# source("tbl_gt.R")
table_academics <- bwu::tbl_gt(
  data,
  table_name = "table_academics",
  # title = "Academic Skills",
  # tab_stubhead = gt::md("**Battery/Scale**"),
  source_note = source_note
)
table_academics
# gt::tab_info(table_academics)

gt::gtsave(table_academics, glue("table_academics", ".png"), expand = 10)
gt::gtsave(table_academics, glue("table_academics", ".pdf"), expand = 10)
```

```{=typst}
<qtbl-academics>
#figure([#image("table_academics.png", width: 70%)],
  caption: [
    Academic Achievement Test Scores
  ],
  kind: "qtbl",
  supplement: [Table],
)
```

```{r}
#| label: fig-academics
#| eval: true
#| fig-cap: "_Reading ability_ consists of three interrelated abilities: decoding, comprehension, and fluency. _Writing ability_ can be described in terms of spelling, grammar, expression of ideas, and writing fluency. _Math ability_ can be described in terms of calculation skills, applied problem solving, and math fluency."

# plots
xfun::pkg_attach(c(
  "gt", "tidyverse", "glue", "webshot2", "ggplot2", "ggthemes",
  "scales", "bwu", "patchwork"
))

# data for dotplot
data_dotplot <- dplyr::filter(data, !is.na(percentile))

# will need to change these for each domain
fig_academics <- bwu::dotplot(
  data = data_dotplot,
  x = data_dotplot$z_mean_narrow,
  y = data_dotplot$narrow,
  fill = x
)
fig_academics
ggplot2::ggsave("fig_academics.png")
ggplot2::ggsave("fig_academics.pdf")
```

```{r}
#| label: _tbl-md-academics
#| eval: false
#| tbl-cap: "Academic Skills"

# markdown table; change label if want to use
markdown_table_typst <- function(data) {
  data.frame(
    data
  ) |>
    kableExtra::kbl(
      format = "markdown",
      table.envir = "figure",
      longtable = FALSE,
      booktabs = TRUE,
      linesep = "",
      align = c("lccc"),
      col.names = c("**Scale**", "**Score**", "**‰ Rank**", "**Range**")
    )
}
tbl_md <- markdown_table_typst(data[, c(2, 4, 5, 6)])
tbl_md
```
```{r}
#| label: csv-academics
academics <- data[, c(2, 4, 5, 6)]
readr::write_csv(academics, "academics.csv", col_names = FALSE)
```
