---
title-meta: verbal
execute:
  warning: false
  echo: false
  message: false
format:
  typst:
    keep-typ: true
  pdf:
    keep-md: true
    keep-tex: true
  html: 
    toc: true
params:
  pheno: "verbal"
  return_plot: TRUE
---

<!-- ## Verbal/Language -->

{{< include _04_verbal_text.qmd >}}

```{r}
#| label: data-verbal
library(bwu)
# read and filter data
pheno <- "verbal"
data <- bwu::read_data(pheno = pheno)
domains <- c("Verbal/Language")
scales <- c(
  "Academic Language Readiness Index",
  "Auditory Comprehension Colors",
  "Auditory Comprehension Colors/Shapes/Numbers",
  "Auditory Comprehension Shapes",
  "Auditory Comprehension",
  "Basic Concepts",
  "Bill Payment",
  "Body Part Identification",
  "Body Part Naming",
  "Category Fluency",
  "Comprehension of Instructions",
  "Comprehension",
  "Core Language Score",
  "D-KEFS Color Naming",
  "D-KEFS Word Reading",
  "Descriptive Pragmatics Profile",
  "Early Literacy Index",
  "Expressive Language Index",
  "Expressive Vocabulary",
  "Following Directions",
  "Information",
  "Language Content Index",
  "Language Domain",
  "Language Index",
  "Language Structure Index",
  "Letter Fluency",
  "NAB Language Index",
  "Naming Phonemic Cuing",
  "Naming Semantic Cuing",
  "Naming vs Identification",
  "Naming",
  "Oral Production",
  "Oromotor Sequences",
  "Phonological Awareness",
  "Picture Naming",
  "Preliteracy Rating Scale",
  "Reading Comprehension",
  "Recalling Sentences",
  "Receptive Language Index",
  "Receptive Vocabulary",
  "Semantic Fluency",
  "Sentence Comprehension",
  "Similarities",
  "Speeded Naming Correct",
  "Speeded Naming Errors",
  "Speeded Naming Time",
  "Speeded Naming",
  "Vocabulary",
  "Word Classes",
  "Word Generation-Initial Letter",
  "Word Generation-Semantic",
  "Word Generation",
  "Word Structure",
  "Writing"
)
data <- bwu::filter_data(data, domain = domains, scale = scales)
```

```{r}
#| label: text-verbal
#| cache: true

# Concatenate text from neuro*.csv files per scale and domain
bwu::cat_neuropsych_results(data, file = "_04_verbal_raw.qmd")
```

```{r}
#| label: qtbl-verbal
#| dev: tikz
#| fig-process: pdf2png
options(tikzDefaultEngine = "xetex")

# footnotes
fn_scaled_score <- gt::md("Scaled Score: Mean = 10 [50th‰], SD ± 3 [16th‰, 84th‰]")
fn_standard_score <- gt::md("Index Score: Mean = 100 [50th‰], SD ± 15 [16th‰, 84th‰]")
fn_t_score <- gt::md("*T* Score: Mean = 50 [50th‰], SD ± 10 [16th‰, 84th‰]")
fn_z_score <- "*z* Score: Mean = 0 [50th‰], SD ± 1 [16th‰, 84th‰]"

pheno <- "verbal"
table_name <- "table_verbal"
# grp_verbal <- list(
#   "scaled_score" = c("WAIS-IV"),
#   "standard_score" = c("NAB"),
#   "t_score" = c("NAB", "NIH EXAMINER")
# )
grp_scaled_score <- c("WAIS-IV")
grp_standard_score <- c("NAB")
grp_t_score <- c("NAB", "NIH EXAMINER")
vertical_padding <- 0.18
multiline <- TRUE

# source(here::here("R", "tbl_gt.R"))
bwu::tbl_gt(data,
  pheno = pheno,
  table_name = table_name,
  vertical_padding = vertical_padding,
  fn_scaled_score = fn_scaled_score,
  fn_standard_score = fn_standard_score,
  fn_t_score = fn_t_score,
  grp_scaled_score = grp_scaled_score,
  grp_standard_score = grp_standard_score,
  grp_t_score = grp_t_score,
  multiline = multiline
)
```

```{r}
#| label: fig-verbal
#| eval: true
#| fig-asp: 0.70
#| fig-cap: "Verbal and language functioning refers to the ability to access and apply acquired word knowledge, to verbalize meaningful concepts, to understand complex multistep instructions, to think about verbal information, and to express oneself using words."

# Arguments
pheno <- "verbal"
verbal <- dplyr::filter(data, subdomain != "Language")
data <- verbal
x <- data$z_mean_subdomain
y <- data$subdomain
colors <- NULL
return_plot <- TRUE
filename <- "fig_verbal.svg"

# Make dotplot
bwu::dotplot(
  data = data,
  x = x,
  y = y,
  colors = colors,
  return_plot = return_plot,
  filename = filename
)
```

```{=typst}
#let domain(title: none, file_qtbl, file_fig) = {
  let font = (font: "Fira Sans", size: 0.80em)
  set text(..font)
    grid(
      columns: (50%, 50%),
      gutter: 8pt,
        figure([#image(file_qtbl)],
          caption: [#title],
          caption-pos: top,
          kind: "qtbl",
          supplement: [*Table*],
          ),
        figure([#image(file_fig)],
          caption: [
            Verbal and language functioning refers to the ability to access and apply acquired word knowledge, to verbalize meaningful concepts, to understand complex multistep instructions, to think about verbal information, and to express oneself using words.
            ],
          placement: bottom,
          kind: "image",
          supplement: [*Fig.*],
          gap: 0.5em,
        ),
      )
  }
```

```{=typst}
#let title = "Verbal/Language"
#let file_qtbl = "table_verbal.png"
#let file_fig = "_04_verbal_files/figure-typst/fig-verbal-1.svg"
#domain(
  title: [#title Test Scores],
  file_qtbl,
  file_fig
  )
```
