---
title-meta: executive
execute:
  warning: false
  echo: false
  message: false
format:
  typst:
    keep-typ: true
  pdf:
    keep-md: true
    keep-tex: true
  html: 
    toc: true
params:
  pheno: "executive"
  return_plot: TRUE
---

<!-- ## Attention/Executive -->

{{< include _06_executive_text.qmd >}}

```{r}
#| label: data-executive

# read and filter data
pheno <- "executive"
data <- bwu::read_data(pheno = pheno)
domains <- "Attention/Executive"
scales <- c(
  "Animal Coding",
  "Arithmetic",
  "Attention Domain",
  "Attention Index",
  "Auditory Working Memory (AWMI)",
  "Bug Search",
  "Cancellation Random",
  "Cancellation Structured",
  "Cancellation",
  "Categories",
  "Category Fluency",
  "Clock Drawing",
  "Coding",
  "Comprehension",
  "CVLT-3 Total Intrusions",
  "CVLT-3 Total Repetitions",
  "D-KEFS Color Naming",
  "D-KEFS Inhibition Total Errors",
  "D-KEFS Inhibition",
  "D-KEFS Switching Total Errors",
  "D-KEFS Switching",
  "D-KEFS Word Reading",
  "Digit Span Backward",
  "Digit Span Forward",
  "Digit Span Sequencing",
  "Digit Span",
  "Digits Backward Longest Span",
  "Digits Backward",
  "Digits Forward Longest Span",
  "Digits Forward",
  "Dots",
  "Driving Scenes",
  "Executive Functions Domain",
  "Judgment",
  "Letter Fluency",
  "Letter-Number Sequencing",
  "Longest Digit Span Backward",
  "Longest Digit Span Forward",
  "Longest Digit Span Sequence",
  "Longest Letter-Number Sequence",
  "Matrix Reasoning",
  "Mazes",
  "NAB Attention Index",
  "NAB Executive Functions Index",
  "Numbers & Letters Part A Efficiency",
  "Numbers & Letters Part A Errors",
  "Numbers & Letters Part A Speed",
  "Numbers & Letters Part B Efficiency",
  "Numbers & Letters Part C Efficiency",
  "Numbers & Letters Part D Disruption",
  "Numbers & Letters Part D Efficiency",
  "Orientation",
  "Picture Memory",
  "Picture Span",
  "Processing Speed (PSI)",
  "ROCFT Copy",
  "Similarities",
  "Spatial Addition",
  "Spatial Span",
  "Symbol Search",
  "Symbol Span",
  "TMT, Part A",
  "TMT, Part B",
  "Total Deviation Score",
  "Unstructured Task",
  "Word Generation",
  "Word Generation Perseverations",
  "Working Memory (WMI)",
  "Zoo Locations"
)
data <- bwu::filter_data(data, domain = domains, scale = scales)
```

```{r}
#| label: text-executive
#| cache: true

# concatenate text for neuropsych results and insert into Quarto/Markdown files
bwu::cat_neuropsych_results(data, file = "_06_executive_raw.qmd")
```

```{r}
#| label: qtbl-executive
#| dev: tikz
#| fig-process: pdf2png
options(tikzDefaultEngine = "xetex")

fn_standard_score <- gt::md("Standard Score: Mean = 100 [50th‰], SD ± 15 [16th‰, 84th‰]")
fn_t_score <- gt::md("*T* Score: Mean = 50 [50th‰], SD ± 10 [16th‰, 84th‰]")
fn_scaled_score <- gt::md("Scaled Score: Mean = 10 [50th‰], SD ± 3 [16th‰, 84th‰]")
fn_z_score <- gt::md("*z* Score: Mean = 0 [50th‰], SD ± 1 [16th‰, 84th‰]")

pheno <- "executive"
table_name <- "table_executive"
# more filtering for exe tables
data <- dplyr::filter(data, test_name != "CVLT-3 Brief") |>
  dplyr::filter(scale != "Orientation") |>
  dplyr::filter(scale %in% c(
    "NAB Attention Index",
    "Digits Forward",
    # "Digits Forward Longest Span",
    "Digits Backward",
    # "Digits Backward Longest Span",
    "Dots",
    "Numbers & Letters Part A Efficiency",
    "Numbers & Letters Part B Efficiency",
    "Numbers & Letters Part C Efficiency",
    "Numbers & Letters Part D Efficiency",
    "Driving Scenes",
    "NAB Executive Functions Index",
    "Mazes",
    "Categories",
    "Word Generation",
    # "Word Generation Perseverations",
    "Judgment",
    "Working Memory (WMI)",
    "Arithmetic",
    "Digit Span",
    "Longest Digit Span Forward",
    "Longest Digit Span Backward",
    "Longest Digit Span Sequence",
    "Letter-Number Sequencing",
    "Symbol Span",
    "Spatial Span",
    "Picture Span",
    "Processing Speed (PSI)",
    "Coding",
    "Cancellation",
    "Symbol Search",
    "TMT, Part A",
    "TMT, Part B",
    "Unstructured Task",
    "Attention Index"
  ))

pheno <- "executive"
table_name <- "table_executive"
grp_standard_score <- c("NAB")
grp_t_score <- c("NIH EXAMINER", "NAB", "Trail Making Test")
grp_scaled_score <- c("WAIS-IV")

grp_executive <- list(
  "scaled_score" = c("WAIS-IV"),
  "standard_score" = c("NAB"),
  "t_score" = c("NIH EXAMINER", "NAB", "Trail Making Test")
)

fn_scaled_score <- gt::md("Scaled Score: Mean = 10 [50th‰], SD ± 3 [16th‰, 84th‰]")
fn_standard_score <- gt::md("Standard Score: Mean = 100 [50th‰], SD ± 15 [16th‰, 84th‰]")
fn_t_score <- gt::md("*T* Score: Mean = 50 [50th‰], SD ± 10 [16th‰, 84th‰]")
fn_z_score <- gt::md("*z* Score: Mean = 0 [50th‰], SD ± 1 [16th‰, 84th‰]")

source(here::here("R", "tbl_gt.R"))
bwu::tbl_gt(data,
  pheno = pheno,
  table_name = table_name,
  vertical_padding = 0.20,
  fn_scaled_score = fn_scaled_score,
  fn_standard_score = fn_standard_score,
  fn_t_score = fn_t_score,
  fn_z_score = fn_z_score,
  grp_standard_score = grp_standard_score,
  grp_t_score = grp_t_score,
  grp_scaled_score = grp_scaled_score,
  multiline = TRUE
)
```

```{r}
#| label: fig-executive
#| eval: true
#| fig-asp: 1.0
#| fig-cap: "Attention and executive functions are essential for successful cognitive functioning, enabling us to perform everyday tasks, handle academic challenges, solve problems, manage our emotions, and interact effectively with others and our environment."

# Arguments
pheno <- "executive"
executive <- dplyr::filter(data, !is.na(percentile))
data <- executive
x <- data$z_mean_subdomain
y <- data$subdomain
colors <- NULL
return_plot <- FALSE
filename <- "svg"
z_score_label <- "*z* Score: Mean = 0 [50th‰], SD ± 1 [16th‰, 84th‰]"

source(here::here("R", "dotplot.R"))
dotplot(
  data = data,
  pheno = pheno,
  x = x,
  y = y,
  colors = colors,
  return_plot = return_plot,
  filename = filename,
  z_score_label = z_score_label
)
```

```{=typst}
#let domain(title: none, file_qtbl, file_fig) = {
  let font = (font: "Fira Sans", size: 0.80em)
  set text(..font)
    grid(
      columns: (50%, 50%),
      gutter: 8pt,
        figure([#image(file_qtbl)],
          caption: [#title],
          caption-pos: top,
          kind: "qtbl",
          supplement: [*Table*],
          ),
        figure([#image(file_fig)],
          caption: [
            Attention and executive functions are essential for successful
            cognitive functioning, enabling us to perform everyday tasks, handle
            academic challenges, solve problems, manage our emotions, and
            interact effectively with others and our environment.
            ],
          placement: bottom,
          kind: "image",
          supplement: [*Fig.*],
          gap: 0.5em,
        ),
      )
  }
```
```{=typst}
#let title = "Attention/Executive"
#let file_qtbl = "table_executive.png"
#let file_fig = "_06_executive_files/figure-typst/fig-executive-1.svg"
#domain(
  title: [#title Test Scores],
  file_qtbl,
  file_fig
  )
```
