---
execute:
  cache: true
---

<<PROMPT>>

Summarize and interpret these neuropsychological test scores related to
attention and executive functioning. For scores that are Below Average, give a brief
example of how this could impact the patient's daily functioning.
Organize your summary and interpretation from scores that are Above Average to
Below Average to delineate relative strengths and weaknesses, respectively.

<<EXAMPLE>>

### Attentional Skills
- _Attention Index:_ Average; Biggie's general attentional
capacity is in line with typical expectations.
- _Auditory Attentional Capacity:_ High Average (9 digits forward). This indicates that Biggie has a strong ability to focus and maintain attention when receiving auditory information.
- _Efficiency in Selective Attention:_ Average; Biggie can focus on specific details and ignore irrelevant information at an average efficiency.
- _Scanning, Divided Attention, Cognitive Flexibility:_
Average; This signifies that Biggie can divide their attention among
multiple tasks, adapt to new information, and visually track moving objects to
an average degree (i.e., attentional fluency).
- _Divided Attention, Information Processing Speed, Inhibition:_ Average; This
indicates a typical capacity to multitask, process information, and control
impulses (i.e., attentional fluency).

### Working Memory
- _Working Memory for Orally Presented Information:_ High Average (7 digits
backward). Biggie can effectively retain and process spoken information in their
short-term memory. 
- _Maintenance and Resequencing of Verbal Information:_
Exceptionally High; This showcases a strong ability to hold onto and rearrange
sequences of numbers and letters in working memory.

### Processing Speed
- _Psychomotor Speed:_ Low Average; Biggie might be somewhat slower in
activities that require rapid and coordinated physical movements.
- _Efficiency of Psychomotor Speed, Visual Scanning Ability, and Visual-Motor Coordination:_ High Average; Biggie possesses good visual skills and hand-eye coordination which are important in activities like reading and fine motor tasks.

### Executive Skills
- _Executive Functions Index:_ Average; Across various executive
functions, Biggie's performance is consistent with normative expectations.
- _Strategic Planning and Organization:_ High Average; Biggie can plan and
organize actions well before executing them, reflecting an ability to anticipate
future events and needs.
- _Planning, Foresight, Inhibition, and Psychomotor Speed:_ Average; Biggie's ability
to plan ahead, inhibit impulses, and move with purpose and speed is typical.

<<START>>

An overall screening measure of the examinee's attentional functioning was Average.
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Average range.
Orientation to person, place, time, and situation was intact.
Self-monitoring and perseverative tendencies was Average.
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average.
NA
NA
NA
NA
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was Average.
A composite measure of executive skills involving planning, inhibition, speed/fluency, and generativity fell in the Average range.
NA
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range.
Retrieval fluency, ideational fluency, and generativity was Average.
NA
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average.
An overall measure of efficiency in performing a selective attention letter cancellation task was Average.
Psychomotor speed was Low Average.
NA
Auditory attentional capacity was High Average (9 digits forward).
Working memory for orally presented information was High Average (7 digits backward).
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the High Average range.
Auditory attentional capacity, or how much information can be processed at once was High Average.
Total number of repetitive response errors was High Average.
A measure of both attentional capacity and working memory was High Average.
Basic psychomotor processing speed was High Average.
Total number of intrusive response errors was High Average.
NA
NA
An overall screening measure of the examinee's attentional functioning was Average.
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Average range.
Orientation to person, place, time, and situation was intact.
Self-monitoring and perseverative tendencies was Average.
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average.
NA
NA
NA
NA
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was Average.
A composite measure of executive skills involving planning, inhibition, speed/fluency, and generativity fell in the Average range.
NA
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range.
Retrieval fluency, ideational fluency, and generativity was Average.
NA
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average.
An overall measure of efficiency in performing a selective attention letter cancellation task was Average.
Psychomotor speed was Low Average.
NA
Auditory attentional capacity was High Average (9 digits forward).
Working memory for orally presented information was High Average (7 digits backward).
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the High Average range.
Auditory attentional capacity, or how much information can be processed at once was High Average.
Total number of repetitive response errors was High Average.
A measure of both attentional capacity and working memory was High Average.
Basic psychomotor processing speed was High Average.
Total number of intrusive response errors was High Average.
NA
NA
An overall screening measure of the examinee's attentional functioning was Average.
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Average range.
Orientation to person, place, time, and situation was intact.
Self-monitoring and perseverative tendencies was Average.
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average.
NA
NA
NA
NA
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was Average.
A composite measure of executive skills involving planning, inhibition, speed/fluency, and generativity fell in the Average range.
NA
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range.
Retrieval fluency, ideational fluency, and generativity was Average.
NA
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average.
An overall measure of efficiency in performing a selective attention letter cancellation task was Average.
Psychomotor speed was Low Average.
NA
Auditory attentional capacity was High Average (9 digits forward).
Working memory for orally presented information was High Average (7 digits backward).
Strategic planning and organization aptitude to formulate an action in advance of performance or intended performance fell within the High Average range.
Auditory attentional capacity, or how much information can be processed at once was High Average.
Total number of repetitive response errors was High Average.
A measure of both attentional capacity and working memory was High Average.
Basic psychomotor processing speed was High Average.
Total number of intrusive response errors was High Average.
NA
NA
An overall screening measure of the examinee's attentional functioning was Average.
Planning and foresight, inhibition, and psychomotor speed examined through a series of maze-tracing tasks fell in the Average range.
Orientation to person, place, time, and situation was intact.
Self-monitoring and perseverative tendencies was Average.
Scanning, visuomotor tracking, divided attention, and cognitive flexibility was Average.
NA
NA
NA
NA
A marker of reduced focus, or selective attention, distractibility, or reduced concentration, and diminished sustained attention was Average.
A composite measure of executive skills involving planning, inhibition, speed/fluency, and generativity fell in the Average range.
NA
Judgment and decisional capacity about issues and situations likely to be encountered in daily life fell within the Average range.
Retrieval fluency, ideational fluency, and generativity was Average.
NA
(ref:first-name)'s performance on a complex measure of divided attention, information processing speed, and inhibition was Average.
An overall measure of efficiency in performing a selective attention letter cancellation task was Average.
Psychomotor speed was Low Average.
NA
