---
title-meta: memory
execute:
  warning: false
  echo: false
  message: false
format:
  typst:
    keep-typ: true
  pdf:
    keep-md: true
    keep-tex: true
  html: 
    toc: true
params:
  pheno: "memory"
  return_plot: TRUE
---

<!-- ## Memory -->

{{< include _07_memory_text.qmd >}}

```{r}
#| label: data-memory
pheno <- "memory"
data <- bwu::read_data(pheno = pheno)
domains <- c("Memory")
scales <- c(
  "CVLT-3 Forced-Choice Recognition Hits",
  "CVLT-3 Total Intrusions",
  "CVLT-3 Total Repetitions",
  "Daily Living Memory Delayed Recall",
  "Daily Living Memory Immediate Recall",
  "Delayed Memory Index",
  "Designs I",
  "Designs II",
  "Figure Recall",
  "Immediate Memory Index",
  "List B Correct",
  "List B Free Recall Correct",
  "List Learning Immediate Recall",
  "List Learning Long Delayed Recall",
  "List Learning Short Delayed Recall",
  "List Learning",
  "List Recall",
  "List Recognition",
  "Logical Memory I",
  "Logical Memory II",
  "Long Delay Cued Recall",
  "Long Delay Free Recall",
  "Long-Delay Cued Recall",
  "Long-Delay Free Recall",
  "Long-Delay Recognition Discriminability",
  "Long-Delay Recognition Response Bias",
  "Memory Domain",
  "Memory for Designs Content",
  "Memory for Designs Delayed Content",
  "Memory for Designs Delayed memory",
  "Memory for Designs Delayed",
  "Memory for Designs memory",
  "Memory for Designs",
  "Memory for Faces Delayed",
  "Memory for Faces",
  "NAB Memory Index",
  "Narrative Memory Free and Cued Recall",
  "Narrative Memory Free Recall",
  "Narrative Memory Recall",
  "Narrative Memory Recognition",
  "Recognition Discriminability (d')",
  # "Recognition Discriminability Nonparametric",
  "ROCFT Delayed Recall",
  "Sentence Repetition",
  "Shape Learning Delayed Recognition",
  "Shape Learning Immediate Recognition",
  # "Shape Learning Percent Retention",
  "Short Delay Cued Recall",
  "Short Delay Free Recall",
  "Short-Delay Cued Recall",
  "Short-Delay Free Recall",
  "Story Learning Delayed Recall",
  "Story Learning Immediate Recall",
  # "Story Learning Percent Retention",
  "Story Memory",
  "Story Recall",
  # "Total False Positives",
  # "Total Hits",
  "Total Intrusions",
  "Total Repetitions",
  # "Trial 1 Correct",
  # "Trial 1 Free Recall Correct",
  # "Trial 2 Correct",
  # "Trial 3 Correct",
  # "Trial 4 Correct",
  # "Trial 5 Correct",
  # "Trial 5 Free Recall Correct",
  "Trials 1-4 Correct",
  "Trials 1-5 Correct",
  "Trials 1-5 Free Recall Correct",
  "Visual Reproduction I",
  "Visual Reproduction II",
  "Word List Interference-Recall",
  "Word List Interference-Repetition"
)
data <-
  bwu::filter_data(
    data,
    domain = domains,
    scale = scales
  )
```


```{r}
#| label: text-memory
#| cache: true

# Concatenate text from neuro*.csv files per scale and domain
# Glue results together and insert into text
bwu::cat_neuropsych_results(data, file = "_07_memory_raw.qmd")
```

```{r}
#| label: qtbl-memory
#| dev: tikz
#| fig-process: pdf2png
options(tikzDefaultEngine = "xetex")

# footnotes
fn_t_score <- gt::md(
  "*T* Score (Mean = 50, SD = 10)"
)
fn_scaled_score <- gt::md("Scaled Score: Mean = 10 [50th‰], SD ± 3 [16th‰, 84th‰]")
fn_standard_score <- gt::md("Standard Score: Mean = 100 [50th‰], SD ± 15 [16th‰, 84th‰]")
fn_z_score <- gt::md("*z* Score: Mean = 0 [50th‰], SD ± 1 [16th‰, 84th‰]")

pheno <- "memory"
table_name <- "table_memory"
grp_standard_score <- c("NAB", "CVLT-3 Brief")
grp_t_score <- c("NAB", "Rey Complex Figure")
grp_scaled_score <- c("CVLT-3 Brief")

memory <- bwu::tbl_gt(data,
  pheno = pheno,
  table_name = table_name,
  vertical_padding = 0.25,
  grp_standard_score = grp_standard_score,
  grp_t_score = grp_t_score,
  grp_scaled_score = grp_scaled_score,
  multiline = TRUE
)
```

```{r}
#| label: fig-memory
#| eval: true
#| fig-asp: 1.0
#| fig-cap: "Learning and memory refer to the rate and ease with which new information (e.g., facts, stories, lists, faces, names) can be encoded, stored, and later recalled from long-term memory."

exclude <- c("CVLT-3 Total Intrusions", "CVLT-3 Total Repetitions", "CVLT-3 Forced-Choice Recognition Hits")

# Arguments
pheno <- "memory"
memory <- data |> 
  dplyr::filter(!is.na(percentile)) |> 
  dplyr::filter(scale != "NAB Memory Index") |> 
  dplyr::filter(!scale %in% exclude)

data <- memory
x <- data$z_mean_narrow
y <- data$narrow
colors <- NULL
return_plot <- TRUE
filename <- "svg"

# Make dotplot
bwu::make_dotplot_typ(
  data = data,
  pheno = pheno,
  x = x,
  y = y,
  colors = colors,
  return_plot = return_plot,
  filename = filename
)
```


```{=typst}
#let domain(title: none, file_qtbl, file_fig) = {
  let font = (font: "Fira Sans", size: 9pt)
  set text(..font)
  grid(
    columns: (50%, 50%),
    gutter: 8pt,
  figure([#image(file_qtbl)],
    caption: [#title],
    caption-pos: top,
    kind: "qtbl",
    supplement: [*Table*],
    ),
  figure([#image(file_fig)],
    caption: [
      Learning and memory refer to the rate and ease with which new information
      (e.g., facts, stories, lists, faces, names) can be encoded, stored, and
      later recalled from long-term memory.
      ],
      kind: "image",
      supplement: [*Fig.*],
      placement: bottom,
      gap: 0.5em,
      ),
  )
}
```

```{=typst}
#let title = "Learning and Memory"
#let file_qtbl = "table_memory.png"
#let file_fig = "_07_memory_files/figure-typst/fig-memory-1.svg"
#domain(
  title: [#title Test Scores],
  file_qtbl,
  file_fig
)
```
