---
title-meta: adhd
execute:
  warning: false
  echo: false
  message: false
format:
  typst:
    keep-typ: true
  pdf:
    keep-md: true
    keep-tex: true
params:
  pheno: "adhd"
  return_plot: TRUE
---

<!-- ## ADHD/Executive Functioning -->

{{< include _10_adhd_text.qmd >}}

```{r}
#| label: data-adhd
pheno <- "adhd"
data <- bwu::read_data(pheno = pheno)
```

```{r}
#| label: filter-adhd

# ADHD/EF Scales
scales <- c(
  "Action",
  "Activation",
  "ADHD Index",
  "Attention",
  "CAARS-OR ADHD Index",
  "CAARS-OR DSM-5 ADHD Symptoms Total",
  "CAARS-OR DSM-5 Hyperactive-Impulsive Symptoms",
  "CAARS-OR DSM-5 Inattentive Symptoms",
  "CAARS-OR Hyperactivity/Restlessness",
  "CAARS-OR Impulsivity/Emotional Lability",
  "CAARS-OR Inattention/Memory Problems",
  "CAARS-OR Problems with Self-Concept",
  "CAARS-SR ADHD Index",
  "CAARS-SR DSM-5 ADHD Symptoms Total",
  "CAARS-SR DSM-5 Hyperactive-Impulsive Symptoms",
  "CAARS-SR DSM-5 Inattentive Symptoms",
  "CAARS-SR Hyperactivity/Restlessness",
  "CAARS-SR Impulsivity/Emotional Lability",
  "CAARS-SR Inattention/Memory Problems",
  "CAARS-SR Problems with Self-Concept",
  "CEFI-OR Attention",
  "CEFI-OR Emotion Regulation",
  "CEFI-OR Flexibility",
  "CEFI-OR Full Scale",
  "CEFI-OR Inhibitory Control",
  "CEFI-OR Initiation",
  "CEFI-OR Organization",
  "CEFI-OR Planning",
  "CEFI-OR Self-Monitoring",
  "CEFI-OR Working Memory",
  "CEFI-SR Attention",
  "CEFI-SR Emotion Regulation",
  "CEFI-SR Flexibility",
  "CEFI-SR Full Scale",
  "CEFI-SR Inhibitory Control",
  "CEFI-SR Initiation",
  "CEFI-SR Organization",
  "CEFI-SR Planning",
  "CEFI-SR Self-Monitoring",
  "CEFI-SR Working Memory",
  "DSM-5 ADHD Symptoms Total",
  "DSM-5 Hyperactive-Impulsive Symptoms",
  "DSM-5 Inattentive Symptoms",
  "Effort",
  "Emotion Regulation",
  "Emotion",
  "Flexibility",
  "Focus",
  "Full Scale",
  "Hyperactivity/Restlessness",
  "Impulsivity/Emotional Lability",
  "Inattention/Memory Problems",
  "Inhibitory Control",
  "Initiation",
  "Memory",
  "Organization",
  "Planning",
  "Problems with Self-Concept",
  "Self-Monitoring",
  "Total Composite",
  "Working Memory"
)
# ADHD
domains <- c("ADHD")
data_adhd <- bwu::filter_data(data,
  domain = domains,
  scale = scales
)
# EF
domains <- c("Executive Functioning")
data_ef <- bwu::filter_data(data,
  domain = domains,
  scale = scales
)
# Merge/bind the two data sets
data <- dplyr::bind_rows(data_adhd, data_ef)
```

```{r}
#| label: text-adhd-sr
#| cache: true

# Self-report
data_sr <-
  data |>
  dplyr::filter(test == "cefi_sr" | test == "caars_sr") |>
  dplyr::arrange(dplyr::desc(percentile)) |>
  dplyr::distinct(.keep_all = FALSE)

# Flatten the text
bwu::cat_neuropsych_results(data = data_sr, file = "_10_adhd_raw.qmd")
```

```{r}
#| label: text-adhd-or
#| cache: true

# Observer reports
data_or <-
  data |>
  dplyr::filter(test == "cefi_or" | test == "caars_or") |>
  dplyr::arrange(dplyr::desc(percentile)) |>
  dplyr::distinct(.keep_all = FALSE)

# Flatten the text
bwu::cat_neuropsych_results(data = data_or, file = "_10_adhd_raw.qmd")
```

```{r}
#| label: qtbl-adhd
#| dev: tikz
#| fig-process: pdf2png
options(tikzDefaultEngine = "xetex")

# footnotes
fn_t_score <- gt::md(
  "*T* Score (Mean = 50, SD = 10)"
)
fn_scaled_score <- gt::md("Scaled Score: Mean = 10 [50th‰], SD ± 3 [16th‰, 84th‰]")
fn_standard_score <- gt::md("Standard Score: Mean = 100 [50th‰], SD ± 15 [16th‰, 84th‰]")
fn_z_score <- gt::md("*z* Score: Mean = 0 [50th‰], SD ± 1 [16th‰, 84th‰]")

source_note <- gt::md("*Note:* CAARS: 
Standard scores (Mean = 50, SD = 10), higher scores reflect reduced functioning.

CEFI: Standard scores (Mean = 100, SD = 15), lower scores reflect reduced
functioning.")

pheno <- "adhd"
table_name <- "table_adhd"
grp_standard_score <- c("CEFI Self-Report", "CEFI Observer-Report")
grp_t_score <- c("CAARS Self-Report", "CAARS Observer-Report")

adhd <- bwu::tbl_gt(data,
  pheno = pheno,
  table_name = table_name,
  vertical_padding = 0.25,
  grp_standard_score = grp_standard_score,
  grp_t_score = grp_t_score,
  grp_scaled_score = NULL,
  multiline = TRUE
)
```

```{r}
#| label: fig-adhd
#| eval: true
#| fig-height: 7
#| fig-cap: "Attention and executive functions are multidimensional concepts that contain several related processes. Both concepts require self-regulatory skills and have some common subprocesses; therefore, it is common to treat them together, or even to refer to both processes when talking about one or the other."
#| fig-subcap:
#| - "ADHD"
#| - "Executive Functioning"

# data for caars dotplot
pheno <- "caars"
data_caars <- dplyr::filter(data, filename %in% c("caars_sr.csv", "caars_or.csv"))
colors <- NULL
return_plot <- TRUE
filename <- "svg"

fig_caars <- bwu::make_dotplot_typ(
  data = data_caars,
  pheno = pheno,
  x = data_caars$z_mean_subdomain,
  y = data_caars$subdomain,
  colors = colors,
  return_plot = return_plot,
  filename = filename
)

# data for cefi dotplot
pheno <- "cefi"
data_cefi <- dplyr::filter(data, filename %in% c("cefi_sr.csv", "cefi_or.csv"))

fig_cefi <- bwu::make_dotplot_typ(
  data = data_cefi,
  pheno = pheno,
  x = data_cefi$z_mean_subdomain,
  y = data_cefi$subdomain,
  colors = colors,
  return_plot = return_plot,
  filename = filename
)

# combine plots
library(ggplot2)
library(patchwork)

patchwork <- fig_caars / fig_cefi
patchwork +
  plot_annotation()
```

```{=typst}
#let domain(title: none, file_qtbl, file_fig) = {
  let font = (font: "Fira Sans", size: 9pt)
  set text(..font)
  grid(
  columns: (50%, 50%),
  gutter: 8pt,
figure([#image(file_qtbl)],
  caption: [
    #title
  ],
  caption-pos: top,
  kind: "qtbl",
  supplement: [*Table*],
),
figure(
  placement: bottom,
  caption: [
    Attention and executive functions are multidimensional concepts that contain several related processes. Both concepts require self-regulatory skills and have some common subprocesses; therefore, it is common to treat them together, or even to refer to both processes when talking about one or the other.
  ],
  kind: "image",
  supplement: [
    *Figure*
    ],
  gap: 1em,
  [
    #image(file_fig)
    ],
  ),
)
}
```

```{=typst}
#let title = "ADHD/Executive Functioning"
#let file_qtbl = "table_adhd.png"
#let file_fig = "_10_cefi_files/figure-typst/fig-cefi-1.svg"
#domain(
  title: [#title Rating Scales],
  file_qtbl,
  file_fig
  )
```
