---
title-meta: emotion-raw
execute:
  cache: true
---

<!-- <<PROMPT>>

Summarize and interpret these neuropsychological test scores as if you are an
experienced clinical neuropsychologist. For scores that are below average,
give a brief example of how this could impact the patient's daily life and functioning. Organize your
summary and interpretation from scores that are above average to below average to delineate
relative strengths and weaknesses. -->

<!-- ### Emotional/Behavioral/Personality -->

<!-- <<START>> -->
 
 
Lilith's score on Anxiety-Related Disorders
(reflecting multiple anxiety-disorder diagnoses and broad impairment associated with anxiety) was Above Average. 
Lilith's score on Stress
(individuals may be experiencing a moderate degree of stress as a result of difficulties in some major life area) was Above Average. 
Lilith's score on Phobias
(indicate impairing phobic behaviors, with avoidance of the feared object or situation) was Above Average. 
Lilith's score on Traumatic Stress
(trauma (single or multiple) is the overriding focus of the person's life) was Above Average. 
Lilith's score on Physiological (A)
(high scorers my not psychologically experience themselves as anxious, but show physiological signs that most people associate with anxiety) was Above Average. 
Lilith's score on Egocentricity
(suggest a person who tends to be self-centered and pragmatic in interaction with others) was High Average. 
Lilith's score on Thought Disorder
(suggest problems in concentration and decision-making) was High Average. 
Lilith's score on Social Detachment
(reflects a person who neither desires nor enjoys the meaning to personal relationships) was High Average. 
Lilith's score on Negative Relationships
(person is likely to be bitter and resentful about the way past relationships have gone) was High Average. 
Lilith's score on Anxiety
(reflecting a generalized impairment associated with anxiety) was High Average. 
Lilith's score on Schizophrenia
(associated with an active schizophrenic episode) was High Average. 
Lilith's score on Affective (A)
(high scorers experience a great deal of tension, have difficulty with relaxing and tend to be easily fatigued as a result of high-perceived stress) was High Average. 
Lilith's score on Obsessive-Compulsive
(scores marked rigidity and significant ruminative concerns) was High Average. 
Lilith's score on Self-Harm
(reflect levels of impulsivity and recklessness that become more hazardous as scores rise) was High Average. 
Lilith's score on ALC Estimated Score
() was Average. 
Lilith's score on Cognitive (D)
(a higher scorer is likely to report feeling hopeless and as having failed at most important life tasks) was Average. 
Lilith's score on DRG Estimated Score
() was Average. 
Lilith's score on Somatization
(high scorers describe general lethargy and malaise, and the presentation is one of complaintiveness and dissatisfaction) was Average. 
Lilith's score on Grandiosity
(person may have little capacity to recognize personal limitations, to the point where one is not able to think clearly about one's capabilities) was Average. 
Lilith's score on Hypervigilance
(suggest a person who is pragmatic and skeptical in relationships) was Average. 
Lilith's score on Borderline Features
(behaviors typically associated with borderline personality disorder) was Average. 
Lilith's score on Antisocial Features
(individuals are likely to be impulsive and hostile, perhaps with a history of reckless and/or antisocial acts) was Average. 
Lilith's score on Stimulus-Seeking
(patient is likely to manifest behavior that is reckless and potentially dangerous to himself and/or those around him) was Average. 
Lilith's score on Somatic Complaints
(degree of concern about physical functioning and health matters and the extent of perceived impairment arising from somatic symptoms) was Average. 
Lilith's score on Cognitive (A)
(elevations indicate worry and concern about current (often uncontrollable) issues that compromise the person's ability to concentrate and attend) was Average. 
Lilith's score on Resentment
(increasing tendency to attribute any misfortunes to the neglect of others and to discredit the successes of others as being the result of luck or favoritism) was Average. 
Lilith's score on Drug Problems
(scores are indicative of a person who may use drugs on a fairly regular basis and may have experienced some adverse consequences as a result) was Average. 
Lilith's score on Conversion
(moderate elevations may be seen in neurological disorders with CNS impairment involving sensorimotor problems, MS, CVA/stroke, or neuropsychological associated with chronic alcoholism) was Average. 
Lilith's score on Paranoia
(individuals are likely to be overtly suspicious and hostile) was Average. 
Lilith's score on Dominance
(average scores reflect an individual who is likely to be able to adapt to different interpersonal situations, by being able to both take and relinquish control in these relationships as needed) was Average. 
Lilith's score on Health Concerns
(elevations indicate a poor health may be a major component of the self-image, with the person accustomed to being in the patient role) was Average. 
Lilith's score on Identity Problems
(suggest uncertainty about major life issues and difficulties in developing and maintaining a sense of purpose) was Average. 
Lilith's score on Nonsupport
(social relationships are perceived as offering little support - family relationships may be either distant or combative, whereas friends are generally seen as unavailable or not helpful when needed) was Average. 
Lilith's score on Mania
(scores are associated with disorders such as mania, hypomania, or cyclothymia) was Average. 
Lilith's score on Depression
(person feels hopeless, discouraged and useless) was Average. 
Lilith's score on Irritability
(person is very volatile in response to frustration and his judgment in such situations may be poor) was Average. 
Lilith's score on Warmth
(average scores reflect an individual who is likely to be able to adapt to different interpersonal situations, by being able to tolerate close attachment but also capable of maintaining some distance in relationships as needed) was Average. 
Lilith's score on Psychotic Experiences
(person may strike others as peculiar and eccentric) was Average. 
Lilith's score on Physiological (D)
(elevations suggest a change in level of physical functioning, typically with a disturbance in sleep pattern, a decrease in energy and level of sexual interest and a loss of appetite and/or weight loss) was Average. 
Lilith's score on Activity Level
(this activity level renders the person confused and difficult to understand) was Average. 
Lilith's score on Persecution
(suggest an individual who is quick to feel that they are being treated inequitably and easily believes that there is concerted effort among others to undermine their best interests) was Average. 
Lilith's score on Affective Instability
(a propensity to experience a particular negative affect (anxiety, depression, or anger is the typical response)) was Average. 
Lilith's score on Antisocial Behaviors
(scores suggest a history of difficulties with authority and with social convention) was Average. 
Lilith's score on Affective (D)
(elevations suggest sadness, a loss of interest in normal activities and a loss if one's sense of pleasure in things that were previously enjoyed) was Average. 
Lilith's score on Suicidal Ideation
(scores are typically of an individual who is seen in clinical settings) was Low Average. 
Lilith's score on Physical Aggression
(suggest that losses of temper are more common and that the person is prone to more physical displays of anger, perhaps breaking objects or engaging in physical confrontations) was Low Average. 
Lilith's score on Alcohol Problems
(are indicative of an individual who may drink regularly and may have experienced some adverse consequences as a result) was Low Average. 
Lilith's score on Aggressive Attitude
(suggest an individual who is easily angered and frustrated; others may perceive him as hostile and readily provoked) was Low Average. 
Lilith's score on Aggression
(scores are indicative of an individual who may be seen as impatient, irritable, and quick-tempered) was Low Average. 
Lilith's score on Verbal Aggression
(reflects a person who is assertive and not intimidated by confrontation and, toward the upper end of this range, he may be verbally aggressive) was Low Average. 
Lilith's score on Treatment Rejection
(average scores suggest a person who acknowledges major difficulties in their functioning, and perceives an acute need for help in dealing with these problems) was Below Average.
 
Lilith's score on Anxiety-Related Disorders
(reflecting multiple anxiety-disorder diagnoses and broad impairment associated with anxiety) was Above Average. 
Lilith's score on Stress
(individuals may be experiencing a moderate degree of stress as a result of difficulties in some major life area) was Above Average. 
Lilith's score on Phobias
(indicate impairing phobic behaviors, with avoidance of the feared object or situation) was Above Average. 
Lilith's score on Traumatic Stress
(trauma (single or multiple) is the overriding focus of the person's life) was Above Average. 
Lilith's score on Physiological (A)
(high scorers my not psychologically experience themselves as anxious, but show physiological signs that most people associate with anxiety) was Above Average. 
Lilith's score on Egocentricity
(suggest a person who tends to be self-centered and pragmatic in interaction with others) was High Average. 
Lilith's score on Thought Disorder
(suggest problems in concentration and decision-making) was High Average. 
Lilith's score on Social Detachment
(reflects a person who neither desires nor enjoys the meaning to personal relationships) was High Average. 
Lilith's score on Negative Relationships
(person is likely to be bitter and resentful about the way past relationships have gone) was High Average. 
Lilith's score on Anxiety
(reflecting a generalized impairment associated with anxiety) was High Average. 
Lilith's score on Schizophrenia
(associated with an active schizophrenic episode) was High Average. 
Lilith's score on Affective (A)
(high scorers experience a great deal of tension, have difficulty with relaxing and tend to be easily fatigued as a result of high-perceived stress) was High Average. 
Lilith's score on Obsessive-Compulsive
(scores marked rigidity and significant ruminative concerns) was High Average. 
Lilith's score on Self-Harm
(reflect levels of impulsivity and recklessness that become more hazardous as scores rise) was High Average. 
Lilith's score on ALC Estimated Score
() was Average. 
Lilith's score on Cognitive (D)
(a higher scorer is likely to report feeling hopeless and as having failed at most important life tasks) was Average. 
Lilith's score on DRG Estimated Score
() was Average. 
Lilith's score on Somatization
(high scorers describe general lethargy and malaise, and the presentation is one of complaintiveness and dissatisfaction) was Average. 
Lilith's score on Grandiosity
(person may have little capacity to recognize personal limitations, to the point where one is not able to think clearly about one's capabilities) was Average. 
Lilith's score on Hypervigilance
(suggest a person who is pragmatic and skeptical in relationships) was Average. 
Lilith's score on Borderline Features
(behaviors typically associated with borderline personality disorder) was Average. 
Lilith's score on Antisocial Features
(individuals are likely to be impulsive and hostile, perhaps with a history of reckless and/or antisocial acts) was Average. 
Lilith's score on Stimulus-Seeking
(patient is likely to manifest behavior that is reckless and potentially dangerous to himself and/or those around him) was Average. 
Lilith's score on Somatic Complaints
(degree of concern about physical functioning and health matters and the extent of perceived impairment arising from somatic symptoms) was Average. 
Lilith's score on Cognitive (A)
(elevations indicate worry and concern about current (often uncontrollable) issues that compromise the person's ability to concentrate and attend) was Average. 
Lilith's score on Resentment
(increasing tendency to attribute any misfortunes to the neglect of others and to discredit the successes of others as being the result of luck or favoritism) was Average. 
Lilith's score on Drug Problems
(scores are indicative of a person who may use drugs on a fairly regular basis and may have experienced some adverse consequences as a result) was Average. 
Lilith's score on Conversion
(moderate elevations may be seen in neurological disorders with CNS impairment involving sensorimotor problems, MS, CVA/stroke, or neuropsychological associated with chronic alcoholism) was Average. 
Lilith's score on Paranoia
(individuals are likely to be overtly suspicious and hostile) was Average. 
Lilith's score on Dominance
(average scores reflect an individual who is likely to be able to adapt to different interpersonal situations, by being able to both take and relinquish control in these relationships as needed) was Average. 
Lilith's score on Health Concerns
(elevations indicate a poor health may be a major component of the self-image, with the person accustomed to being in the patient role) was Average. 
Lilith's score on Identity Problems
(suggest uncertainty about major life issues and difficulties in developing and maintaining a sense of purpose) was Average. 
Lilith's score on Nonsupport
(social relationships are perceived as offering little support - family relationships may be either distant or combative, whereas friends are generally seen as unavailable or not helpful when needed) was Average. 
Lilith's score on Mania
(scores are associated with disorders such as mania, hypomania, or cyclothymia) was Average. 
Lilith's score on Depression
(person feels hopeless, discouraged and useless) was Average. 
Lilith's score on Irritability
(person is very volatile in response to frustration and his judgment in such situations may be poor) was Average. 
Lilith's score on Warmth
(average scores reflect an individual who is likely to be able to adapt to different interpersonal situations, by being able to tolerate close attachment but also capable of maintaining some distance in relationships as needed) was Average. 
Lilith's score on Psychotic Experiences
(person may strike others as peculiar and eccentric) was Average. 
Lilith's score on Physiological (D)
(elevations suggest a change in level of physical functioning, typically with a disturbance in sleep pattern, a decrease in energy and level of sexual interest and a loss of appetite and/or weight loss) was Average. 
Lilith's score on Activity Level
(this activity level renders the person confused and difficult to understand) was Average. 
Lilith's score on Persecution
(suggest an individual who is quick to feel that they are being treated inequitably and easily believes that there is concerted effort among others to undermine their best interests) was Average. 
Lilith's score on Affective Instability
(a propensity to experience a particular negative affect (anxiety, depression, or anger is the typical response)) was Average. 
Lilith's score on Antisocial Behaviors
(scores suggest a history of difficulties with authority and with social convention) was Average. 
Lilith's score on Affective (D)
(elevations suggest sadness, a loss of interest in normal activities and a loss if one's sense of pleasure in things that were previously enjoyed) was Average. 
Lilith's score on Suicidal Ideation
(scores are typically of an individual who is seen in clinical settings) was Low Average. 
Lilith's score on Physical Aggression
(suggest that losses of temper are more common and that the person is prone to more physical displays of anger, perhaps breaking objects or engaging in physical confrontations) was Low Average. 
Lilith's score on Alcohol Problems
(are indicative of an individual who may drink regularly and may have experienced some adverse consequences as a result) was Low Average. 
Lilith's score on Aggressive Attitude
(suggest an individual who is easily angered and frustrated; others may perceive him as hostile and readily provoked) was Low Average. 
Lilith's score on Aggression
(scores are indicative of an individual who may be seen as impatient, irritable, and quick-tempered) was Low Average. 
Lilith's score on Verbal Aggression
(reflects a person who is assertive and not intimidated by confrontation and, toward the upper end of this range, he may be verbally aggressive) was Low Average. 
Lilith's score on Treatment Rejection
(average scores suggest a person who acknowledges major difficulties in their functioning, and perceives an acute need for help in dealing with these problems) was Below Average.
