quarto::quarto_render(
  input = "Biggie.qmd",
  execute_params = list(
    patient = "Biggie",
    first_name = "Biggie",
    last_name = "Smalls",
    mrn = 123,
    dob = "10/04/2010",
    doe1 = "2023-07-29",
    doe2 = "2023-08-12",
    doe3 = NULL,
    sex = "female",
    sex_cap = "Female",
    age = 12,
    education = 15,
    handedness = "right",
    referral = "Dr. Dre",
    observer = "Mrs. Wallace",
    observer_relation = "mother",
    he_she = "she",
    he_she_cap = "She",
    his_her = "her",
    his_her_cap = "Her",
    him_her = "her",
    him_her_cap = "Her",
    dx1 = "attention-deficit/hyperactivity disorder (ADHD)",
    dx2 = "anxiety",
    dx3 = "depression"
  ),
  output_file = "Biggie2.pdf"
)
