---
title: NEUROCOGNITIVE EXAMINATION
name: Biggie Shakur
doe: 2023-01-02
patient: Biggie
---

```{r}
#| label: setup
#| include: false
#| cache: false

# Load necessary packages
packages <- c(
  "ggtext", "ggthemes", "glue", "gt", "gtExtras", "hablar", "here",
  "htmlwidgets", "janitor", "knitr", "magick", "png", "manipulateWidget", "quarto",
  "readxl", "rmarkdown", "scales", "snakecase", "stats", "svglite",
  "tidyselect", "tidytext", "tidyverse", "webshot2", "widgetframe", "xfun",
  "yaml", "bwu"
)
xfun::pkg_load2(packages)

# Set knitr options
knitr::opts_knit$set(width = 80, digits = 2, warnPartialMatchArgs = FALSE)
knitr::knit_hooks$set(crop = knitr::hook_pdfcrop)
knitr::knit_hooks$set(optipng = knitr::hook_optipng)

# Set plot hook for LaTeX output
if (identical(knitr:::pandoc_to(), "latex")) {
  knitr::knit_hooks$set(plot = knitr::hook_plot_tex)
}

# Set environment variables with default values
Sys.setenv(PATIENT = "Biggie", RETURN_PLOT = TRUE)
patient <- Sys.getenv("PATIENT")
return_plot <- Sys.getenv("RETURN_PLOT")
```

```{r}
#| label: data-load
#| include: false

file_path <- here::here(patient)
bwu::load_data(here::here(file_path))
neurocog <- readr::read_csv("neurocog.csv")
neurobehav <- readr::read_csv("neurobehav.csv")
neuropsych <- readr::read_csv("neuropsych.csv")
validity <- readr::read_csv("validity.csv")
```


```{=typst}
#let name = [Biggie Shakur]
#let doe = [2023-01-02]
#let patient = [Biggie]
#v(2em, weak: true)
#show block: set par(leading: 0.65em)
#block[
*PATIENT NAME:* #name \
*DATES OF EXAM:* {{< var dx1 >}}, {{< var dx1 >}}, and {{< var dx1 >}} \
]
#show heading.where(level: 1): set align(center)
```

{{< include _00-00_tests.qmd >}}

{{< pagebreak >}}

{{< include _01-00_nse.qmd >}}

<!-- {{< pagebreak >}} -->

# NEUROCOGNITIVE FINDINGS {#sec-nt}

{{< include _02-00_behav-obs.qmd >}}

{{< include _02-01_iq.qmd >}}

{{< include _02-02_academics.qmd >}}

{{< include _02-03_verbal.qmd >}}

{{< include _02-04_spatial.qmd >}}

{{< include _02-05_executive.qmd >}}

{{< include _02-06_memory.qmd >}}

<!-- {{< include _02-07_motor.qmd >}} -->

<!-- {{< include _02-08_social.qmd >}} -->

{{< include _02-09_adhd_adult.qmd >}}

{{< include _02-10_emotion_adult.qmd >}}

<!-- {{< include _02-11_adaptive.qmd >}} -->

<!-- {{< pagebreak >}} -->

{{< include _03-00_sirf.qmd >}}

{{< include _03-00_sirf_text.qmd >}}

{{< include _03-01_recs.qmd >}}

{{< include _03-02_signature.qmd >}}

{{< pagebreak >}}

{{< include _03-03_appendix.qmd >}}
