library(tibble)
library(dplyr)


# Meta --------------------------------------------------------------------

test <- "nepsy2"

# Scale -------------------------------------------------------------------


scale <- c(
  # ATT/EXE 3-4
  "Statue",
  "Statue-Body Movement",
  "Statue-Eye Opening",
  "Statue-Vocalization",
  # ATT/EXE 4-16
  "Clocks",
  "Animal Sorting Correct Sorts",
  "Animal Sorting Errors",
  "Animal Sorting Repeated Sort Errors",
  "Animal Sorting Novel Sort Errors",
  "Animal Sorting",
  "Auditory Attention Correct",
  "Auditory Attention",
  "Auditory Attention Omission Errors",
  "Auditory Attention Commission Errors",
  "Auditory Attention Inhibitory Errors",
  "Response Set Correct",
  "Response Set",
  "Response Set Omission Errors",
  "Response Set Commission Errors",
  "Response Set Inhibitory Errors",
  "AA vs. RS",
  "Naming Time",
  "Naming",
  "Naming Errors",
  "Naming Self-Corrected Errors",
  "Naming Uncorrected Errors",
  "Inhibition Time",
  "Inhibition",
  "Inhibition Errors",
  "Inhibition Self-Corrected Errors",
  "Inhibition Uncorrected Errors",
  "Switching Time",
  "Switching",
  "Switching Errors",
  "Switching Self-Corrected Errors",
  "Switching Uncorrected Errors",
  "Naming vs. Inhibition",
  "Inhibition vs. Switching",
  "Inhibition Total Errors",
  # Language
  "Body Part Naming",
  "Body Part Identification",
  "Naming vs Identification",
  "Oromotor Sequences",
  "Word Generation-Semantic",
  "Word Generation-Initial Letter",
  "Semantic vs. Initial Letter",
  "Comprehension of Instructions",
  "Speeded Naming Time",
  "Speeded Naming Correct",
  "Speeded Naming",
  "Speeded Naming Self-Corrected Errors",
  # Memory
  "Sentence Repetition",
  "Memory for Faces",
  "Memory for Faces Delayed",
  "MF vs. MFD",
  "Word List Interference-Repetition",
  "Word List Interference-Recall",
  "Repetition vs. Recall",
  "List Memory and List Memory Delayed",
  "Narrative Memory Free and Cued Recall",
  "Narrative Memory Free Recall",
  "Narrative Memory Recognition",
  "Free and Cued Recall vs. Recognition",
  "Memory for Designs",
  "Memory for Designs Content",
  "Memory for Designs Spatial",
  "MD Content vs. Spatial",
  "Memory for Designs Delayed",
  "Memory for Designs Delayed Content",
  "Memory for Designs Delayed Spatial",
  "MDD Content vs. Spatial",
  "MD vs. MDD",
  # Sensorimotor
  "Imitating Hand Positions",
  "Imitating Hand Positions-Dominant",
  "Imitating Hand Positions-Nondominant",
  "Visuomotor Precision Time",
  "Visuomotor Precision Errors",
  "Visuomotor Precision",
  "Visuomotor Precision Pencil Lifts",
  "Fingertip Tapping Dominant Hand Repetitions",
  "Fingertip Tapping Dominant Hand Sequences",
  "Fingertip Tapping Nondominant Hand Repetitions",
  "Fingertip Tapping Nondominant Hand Sequences",
  "Fingertip Tapping Dominant Hand",
  "Fingertip Tapping Nondominant Hand",
  "Fingertip Tapping Repetitions",
  "Fingertip Tapping Sequences",
  "Dominant vs. Nondominant",
  "Repetitions vs. Sequences",
  "Visuomotor Precision Time",
  # Visuospatial
  "Design Copying Process Global",
  "Design Copying Process Local",
  "Global vs. Local",
  "Design Copying General",
  "Geometric Puzzles",
  "Arrows",
  "Design Copying General",
  # Social Cognition
  "Affect Recognition",
  "Affect Recognition Happy Errors",
  "Affect Recognition Sad Errors",
  "Affect Recognition Neutral Errors",
  "Affect Recognition Fear Errors",
  "Affect Recognition Angry Errors",
  "Affect Recognition Disgust Errors",
  "Theory of Mind",
  "Theory of Mind Verbal"
)


# Domain ------------------------------------------------------------------

statue <- c("Statue", "Statue-Body Movement", "Statue-Eye Opening", "Statue-Vocalization")


domain <- dplyr::case_when(
  # ATT/EXE"
  scale %in% statue ~ "Attention/Executive",
  scale == "Clocks" ~ "Attention/Executive",
  scale == "Animal Sorting Correct Sorts" ~ "Attention/Executive",
  scale == "Animal Sorting Errors" ~ "Attention/Executive",
  scale == "Animal Sorting Repeated Sort Errors" ~ "Attention/Executive",
  scale == "Animal Sorting Novel Sort Errors" ~ "Attention/Executive",
  scale == "Animal Sorting" ~ "Attention/Executive",
  scale == "Naming Time" ~ "Verbal/Language",
  scale == "Naming" ~ "Verbal/Language",
  scale == "Naming Errors" ~ "Verbal/Language",
  scale == "Naming Self-Corrected Errors" ~ "Attention/Executive",
  scale == "Naming Uncorrected Errors" ~ "Verbal/Language",
  scale == "Inhibition Time" ~ "Attention/Executive",
  scale == "Inhibition" ~ "Attention/Executive",
  scale == "Inhibition Errors" ~ "Attention/Executive",
  scale == "Inhibition Self-Corrected Errors" ~ "Attention/Executive",
  scale == "Inhibition Uncorrected Errors" ~ "Attention/Executive",
  scale == "Switching Time" ~ "Attention/Executive",
  scale == "Switching" ~ "Attention/Executive",
  scale == "Switching Errors" ~ "Attention/Executive",
  scale == "Switching Self-Corrected Errors" ~ "Attention/Executive",
  scale == "Switching Uncorrected Errors" ~ "Attention/Executive",
  scale == "Naming vs. Inhibition" ~ "Attention/Executive",
  scale == "Inhibition vs. Switching" ~ "Attention/Executive",
  scale == "Inhibition Total Errors" ~ "Attention/Executive",
  # LANG
  scale == "Comprehension of Instructions" ~ "Verbal/Language",
  scale == "Speeded Naming Time" ~ "Verbal/Language",
  scale == "Speeded Naming Correct" ~ "Verbal/Language",
  scale == "Speeded Naming" ~ "Verbal/Language",
  scale == "Speeded Naming Self-Corrected Errors" ~ "Attention/Executive",
  scale == "Word Generation-Semantic" ~ "Verbal/Language",
  scale == "Word Generation-Initial Letter" ~ "Verbal/Language",
  scale == "Semantic vs. Initial Letter" ~ "Verbal/Language",
  # MEM
  scale == "Memory for Faces" ~ "Memory",
  scale == "Memory for Faces Delayed" ~ "Memory",
  scale == "Word List Interference Repetition" ~ "Memory",
  scale == "Word List Interference Recall" ~ "Memory",
  scale == "List Memory and List Memory Delayed" ~ "Memory",
  scale == "Narrative Memory Free and Cued Recall" ~ "Memory",
  scale == "Narrative Memory Free Recall" ~ "Memory",
  scale == "Narrative Memory Recognition" ~ "Memory",
  scale == "Recall vs Recognition" ~ "Memory",
  scale == "Memory for Designs" ~ "Memory",
  scale == "Memory for Designs Content" ~ "Memory",
  scale == "Memory for Designs Spatial" ~ "Memory",
  scale == "Memory for Designs Delayed" ~ "Memory",
  scale == "Memory for Designs Delayed Content" ~ "Memory",
  scale == "Memory for Designs Delayed Spatial" ~ "Memory",
  # MOTOR
  scale == "Fingertip Tapping Dominant Hand Repetitions" ~ "Motor",
  scale == "Fingertip Tapping Dominant Hand Sequences" ~ "Motor",
  scale == "Fingertip Tapping Nondominant Hand Repetitions" ~ "Motor",
  scale == "Fingertip Tapping Nondominant Hand Sequences" ~ "Motor",
  scale == "Fingertip Tapping Dominant Hand" ~ "Motor",
  scale == "Fingertip Tapping Nondominant Hand" ~ "Motor",
  scale == "Fingertip Tapping Repetitions" ~ "Motor",
  scale == "Fingertip Tapping Sequences" ~ "Motor",
  scale == "Dominant vs. Nondominant" ~ "Motor",
  scale == "Repetitions vs. Sequences" ~ "Motor",
  scale == "Visuomotor Precision Time" ~ "Motor",
  scale == "Visuomotor Precision Errors" ~ "Motor",
  scale == "Visuomotor Precision" ~ "Motor",
  scale == "Visuomotor Precision Pencil Lifts" ~ "Motor",
  scale == "Imitating Hand Positions" ~ "Motor",
  # SOCIAL
  scale == "Affect Recognition" ~ "Social Cognition",
  scale == "Affect Recognition Happy Errors" ~ "Social Cognition",
  scale == "Affect Recognition Sad Errors" ~ "Social Cognition",
  scale == "Affect Recognition Neutral Errors" ~ "Social Cognition",
  scale == "Affect Recognition Fear Errors" ~ "Social Cognition",
  scale == "Affect Recognition Angry Errors" ~ "Social Cognition",
  scale == "Affect Recognition Disgust Errors" ~ "Social Cognition",
  scale == "Theory of Mind" ~ "Social Cognition",
  scale == "Theory of Mind Verbal" ~ "Social Cognition",
  # SPATIAL
  scale == "Arrows" ~ "Visual Perception/Construction",
  scale == "Design Copying General" ~ "Visual Perception/Construction",
  scale == "Design Copying Process" ~ "Visual Perception/Construction",
  scale == "Design Copying Process Global" ~ "Visual Perception/Construction",
  scale == "Design Copying Process Local" ~ "Visual Perception/Construction",
  scale == "Design Copying Process Motor" ~ "Visual Perception/Construction",
  scale == "Geometric Puzzles" ~ "Visual Perception/Construction",
  TRUE ~ NA_character_
)


# Subdomain ---------------------------------------------------------------


subdomain <- dplyr::case_when(
  # ATT/EXE"
  scale %in% statue ~ "Executive Functioning",
  scale == "Auditory Attention Correct" ~ "Attention",
  scale == "Auditory Attention" ~ "Attention",
  scale == "Auditory Attention Omission Errors" ~ "Response Monitoring",
  scale == "Auditory Attention Commission Errors" ~ "Response Monitoring",
  scale == "Auditory Attention Inhibitory Errors" ~ "Response Monitoring",
  scale == "Response Set Correct" ~ "Attention",
  scale == "Response Set" ~ "Attention",
  scale == "Response Set Omission Errors" ~ "Response Monitoring",
  scale == "Response Set Commission Errors" ~ "Response Monitoring",
  scale == "Response Set Inhibitory Errors" ~ "Response Monitoring",
  scale == "AA vs. RS" ~ "Attention",
  scale == "Clocks" ~ "Executive Functioning", # change all the rest of these
  scale == "Animal Sorting Correct Sorts" ~ "Executive Functioning",
  scale == "Animal Sorting Errors" ~ "Response Monitoring",
  scale == "Animal Sorting Repeated Sort Errors" ~ "Response Monitoring",
  scale == "Animal Sorting Novel Sort Errors" ~ "Response Monitoring",
  scale == "Animal Sorting" ~ "Executive Functioning",
  scale == "Naming Time" ~ "Naming",
  scale == "Naming" ~ "Naming",
  scale == "Naming Errors" ~ "Response Monitoring",
  scale == "Naming Self-Corrected Errors" ~ "Response Monitoring",
  scale == "Naming Uncorrected Errors" ~ "Response Monitoring",
  scale == "Inhibition Time" ~ "Executive Functioning",
  scale == "Inhibition" ~ "Executive Functioning",
  scale == "Inhibition Errors" ~ "Response Monitoring",
  scale == "Inhibition Self-Corrected Errors" ~ "Response Monitoring",
  scale == "Inhibition Uncorrected Errors" ~ "Response Monitoring",
  scale == "Switching Time" ~ "Cognitive Flexibility",
  scale == "Switching" ~ "Cognitive Flexibility",
  scale == "Switching Errors" ~ "Response Monitoring",
  scale == "Switching Self-Corrected Errors" ~ "Response Monitoring",
  scale == "Switching Uncorrected Errors" ~ "Response Monitoring",
  scale == "Naming vs. Inhibition" ~ "Inhibition",
  scale == "Inhibition vs. Switching" ~ "Inhibition vs Switching",
  scale == "Inhibition Total Errors" ~ "Response Monitoring",
  scale == "Sentence Repetition" ~ "Working Memory",
  # Language
  scale == "Comprehension of Instructions" ~ "Comprehension",
  scale == "Speeded Naming Time" ~ "Naming",
  scale == "Speeded Naming Correct" ~ "Naming",
  scale == "Speeded Naming" ~ "Naming",
  scale == "Speeded Naming Self-Corrected Errors" ~ "Response Monitoring",
  scale == "Word Generation-Semantic" ~ "Fluency",
  scale == "Word Generation-Initial Letter" ~ "Fluency",
  scale == "Semantic vs. Initial Letter" ~ "Fluency",
  # MEM
  scale == "Memory for Faces" ~ "Nonverbal Memory",
  scale == "Memory for Faces Delayed" ~ "Nonverbal Memory",
  scale == "Word List Interference-Repetition" ~ "Verbal Memory",
  scale == "Word List Interference-Recall" ~ "Verbal Memory",
  scale == "List Memory and List Memory Delayed" ~ "Verbal Memory",
  scale == "Narrative Memory Free and Cued Recall" ~ "Verbal Memory",
  scale == "Narrative Memory Free Recall" ~ "Verbal Memory",
  scale == "Narrative Memory Recognition" ~ "Verbal Memory",
  scale == "Recall vs Recognition" ~ "",
  scale == "Memory for Designs" ~ "Nonverbal Memory",
  scale == "Memory for Designs Content" ~ "Nonverbal Memory",
  scale == "Memory for Designs Spatial" ~ "Nonverbal Memory",
  scale == "Memory for Designs Delayed" ~ "Nonverbal Memory",
  scale == "Memory for Designs Delayed Content" ~ "Nonverbal Memory",
  scale == "Memory for Designs Delayed Spatial" ~ "Nonverbal Memory",
  # MOTOR
  scale == "Imitating Hand Positions" ~ "Graphomotor Control",
  scale == "Imitating Hand Positions-Dominant" ~ "Graphomotor Control",
  scale == "Imitating Hand Positions-Nondominant" ~ "Graphomotor Control",
  scale == "Fingertip Tapping Dominant Hand Repetitions" ~ "Fine Motor Dexterity",
  scale == "Fingertip Tapping Dominant Hand Sequences" ~ "Fine Motor Dexterity",
  scale == "Fingertip Tapping Nondominant Hand Repetitions" ~ "Fine Motor Dexterity",
  scale == "Fingertip Tapping Nondominant Hand Sequences" ~ "Fine Motor Dexterity",
  scale == "Fingertip Tapping Dominant Hand" ~ "Fine Motor Dexterity",
  scale == "Fingertip Tapping Nondominant Hand" ~ "Fine Motor Dexterity",
  scale == "Fingertip Tapping Repetitions" ~ "Fine Motor Dexterity",
  scale == "Fingertip Tapping Sequences" ~ "Fine Motor Dexterity",
  scale == "Dominant vs. Nondominant" ~ "Dominant vs. Nondominant",
  scale == "Repetitions vs. Sequences" ~ "",
  scale == "Visuomotor Precision Time" ~ "Graphomotor Speed",
  scale == "Visuomotor Precision Errors" ~ "Response Monitoring",
  scale == "Visuomotor Precision" ~ "Graphomotor Speed",
  scale == "Visuomotor Precision Pencil Lifts" ~ "Graphomotor Speed",
  scale == "Imitating Hand Positions" ~ "Motor Imitation",
  # Soc Cog
  scale == "Affect Recognition" ~ "Affect Recognition",
  scale == "Affect Recognition Happy Errors" ~ "Affect Recognition",
  scale == "Affect Recognition Sad Errors" ~ "Affect Recognition",
  scale == "Affect Recognition Neutral Errors" ~ "Affect Recognition",
  scale == "Affect Recognition Fear Errors" ~ "Affect Recognition",
  scale == "Affect Recognition Angry Errors" ~ "Affect Recognition",
  scale == "Affect Recognition Disgust Errors" ~ "Affect Recognition",
  scale == "Theory of Mind" ~ "Theory of Mind",
  scale == "Theory of Mind Verbal" ~ "Theory of Mind",
  # Spatial
  scale == "Arrows" ~ "Visuoperception",
  scale == "Design Copying General" ~ "Visual Processing",
  scale == "Design Copying Process" ~ "Visual Processing",
  scale == "Design Copying Process Global" ~ "Visual Processing",
  scale == "Design Copying Process Local" ~ "Visual Processing",
  scale == "Design Copying Process Motor" ~ "Visual Processing",
  scale == "Global vs. Local" ~ "",
  scale == "Geometric Puzzles" ~ "Visual Processing",
  TRUE ~ NA_character_
)


# Narrow ------------------------------------------------------------------



narrow <- dplyr::case_when(
  scale %in% statue ~ "Inhibition",
  scale == "Auditory Attention Correct" ~ "Attentional Fluency",
  scale == "Auditory Attention" ~ "Attentional Fluency",
  scale == "Auditory Attention Omission Errors" ~ "Response Monitoring",
  scale == "Auditory Attention Commission Errors" ~ "Response Monitoring",
  scale == "Auditory Attention Inhibitory Errors" ~ "Response Monitoring",
  scale == "Response Set Correct" ~ "Attentional Fluency",
  scale == "Response Set" ~ "Attentional Fluency",
  scale == "Response Set Omission Errors" ~ "Response Monitoring",
  scale == "Response Set Commission Errors" ~ "Response Monitoring",
  scale == "Response Set Inhibitory Errors" ~ "Response Monitoring",
  scale == "AA vs. RS" ~ "Attention/Inhibition",
  scale == "Clocks" ~ "Planning",
  scale == "Animal Sorting Correct Sorts" ~ "Concept Formation",
  scale == "Animal Sorting Errors" ~ "Concept Formation",
  scale == "Animal Sorting Repeated Sort Errors" ~ "Concept Formation",
  scale == "Animal Sorting Novel Sort Errors" ~ "Concept Formation",
  scale == "Animal Sorting" ~ "Concept Formation",
  scale == "Naming Time" ~ "Naming Facility",
  scale == "Naming" ~ "Naming Facility",
  scale == "Naming Errors" ~ "Response Monitoring",
  scale == "Naming Self-Corrected Errors" ~ "Response Monitoring",
  scale == "Naming Uncorrected Errors" ~ "Rapid Naming",
  scale == "Inhibition Time" ~ "Inhibition",
  scale == "Inhibition" ~ "Inhibition",
  scale == "Inhibition Errors" ~ "Response Monitoring",
  scale == "Inhibition Self-Corrected Errors" ~ "Response Monitoring",
  scale == "Inhibition Uncorrected Errors" ~ "Response Monitoring",
  scale == "Switching Time" ~ "Cognitive Flexibility",
  scale == "Switching" ~ "Cognitive Flexibility",
  scale == "Switching Errors" ~ "Response Monitoring",
  scale == "Switching Self-Corrected Errors" ~ "Response Monitoring",
  scale == "Switching Uncorrected Errors" ~ "Response Monitoring",
  scale == "Naming vs. Inhibition" ~ "Naming vs Inhib",
  scale == "Inhibition vs. Switching" ~ "Inhib vs Switch",
  scale == "Inhibition Total Errors" ~ "Response Monitoring",
  # Lang
  scale == "Body Part Naming" ~ "Expressive Vocabulary",
  scale == "Body Part Identification" ~ "Expressive Vocabulary",
  scale == "Naming vs Identification" ~ "Expressive Vocabulary",
  scale == "Oromotor Sequences" ~ "Speech Articulation",
  scale == "Comprehension of Instructions" ~ "Listening Ability",
  scale == "Speeded Naming Time" ~ "Naming Facility",
  scale == "Speeded Naming Correct" ~ "Naming Facility",
  scale == "Speeded Naming" ~ "Naming Facility",
  scale == "Speeded Naming Self-Corrected Errors" ~ "Response Monitoring",
  scale == "Word Generation-Semantic" ~ "Semantic Fluency",
  scale == "Word Generation-Initial Letter" ~ "Phonemic Fluency",
  scale == "Semantic vs. Initial Letter" ~ "",
  # MEM
  scale == "Sentence Repetition" ~ "Working Memory",
  scale == "Memory for Faces" ~ "Nonverbal Immediate Recall",
  scale == "Memory for Faces Delayed" ~ "Nonverbal Delayed Recall",
  scale == "Word List Interference-Repetition" ~ "Verbal Associative Learning",
  scale == "Word List Interference-Recall" ~ "Verbal Associative Recall",
  scale == "List Memory and List Memory Delayed" ~ "Verbal Immediate Recall",
  scale == "Narrative Memory Free and Cued Recall" ~ "Verbal Immediate Recall",
  scale == "Narrative Memory Free Recall" ~ "Verbal Immediate Recall",
  scale == "Narrative Memory Recognition" ~ "Verbal Recognitioin",
  scale == "Recall vs Recognition" ~ "",
  scale == "Memory for Designs" ~ "Nonverbal Immediate Recall",
  scale == "Memory for Designs Content" ~ "Nonverbal Immediate Recall",
  scale == "Memory for Designs Spatial" ~ "Nonverbal Immediate Recall",
  scale == "Memory for Designs Delayed" ~ "Nonverbal Delayed Recall",
  scale == "Memory for Designs Delayed Content" ~ "Nonverbal Delayed Recall",
  scale == "Memory for Designs Delayed Spatial" ~ "Nonverbal Delayed Recall",
  # Motor
  scale == "Imitating Hand Positions" ~ "Graphomotor Control",
  scale == "Imitating Hand Positions-Dominant" ~ "Graphomotor Control",
  scale == "Imitating Hand Positions-Nondominant" ~ "Graphomotor Control",
  scale == "Fingertip Tapping Dominant Hand Repetitions" ~ "Finger Dexterity Dominant Hand",
  scale == "Fingertip Tapping Dominant Hand Sequences" ~ "Finger Dexterity Dominant Hand",
  scale == "Fingertip Tapping Nondominant Hand Repetitions" ~ "Finger Dexterity Nondominant Hand",
  scale == "Fingertip Tapping Nondominant Hand Sequences" ~ "Finger Dexterity Nondominant Hand",
  scale == "Fingertip Tapping Dominant Hand" ~ "Fine Motor Dexterity Dominant Hand",
  scale == "Fingertip Tapping Nondominant Hand" ~ "Fine Motor Dexterity Nondominant Hand",
  scale == "Fingertip Tapping Repetitions" ~ "Bilateral Finger Dexterity Repetitions",
  scale == "Fingertip Tapping Sequences" ~ "Bilateral Finger Dexterity Sequencing",
  scale == "Dominant vs. Nondominant" ~ "Dominant vs. Nondominant",
  scale == "Repetitions vs. Sequences" ~ "",
  scale == "Visuomotor Precision Time" ~ "Graphomotor Speed",
  scale == "Visuomotor Precision Errors" ~ "Graphomotor Speed",
  scale == "Visuomotor Precision" ~ "Graphomotor Speed",
  scale == "Visuomotor Precision Pencil Lifts" ~ "Graphomotor Speed",
  scale == "Imitating Hand Positions" ~ "Bilateral Motor Imitation",
  # Soc cog
  scale == "Affect Recognition" ~ "Affect Recognition",
  scale == "Affect Recognition Happy Errors" ~ "Affect Recognition",
  scale == "Affect Recognition Sad Errors" ~ "Affect Recognition",
  scale == "Affect Recognition Neutral Errors" ~ "Affect Recognition",
  scale == "Affect Recognition Fear Errors" ~ "Affect Recognition",
  scale == "Affect Recognition Angry Errors" ~ "Affect Recognition",
  scale == "Affect Recognition Disgust Errors" ~ "Affect Recognition",
  scale == "Theory of Mind" ~ "Theory of Mind",
  scale == "Theory of Mind Verbal" ~ "Theory of Mind",
  # Spatial
  scale == "Arrows" ~ "Visuoperception",
  scale == "Design Copying Process Global" ~ "Visuomotor Integration",
  scale == "Design Copying Process Local" ~ "Visuomotor Integration",
  scale == "Design Copying Process Motor" ~ "Visuomotor Integration",
  scale == "Design Copying General" ~ "Visuomotor Integration",
  scale == "Design Copying Process" ~ "Visuomotor Integration",
  scale == "Geometric Puzzles" ~ "Visualization",
  TRUE ~ NA_character_
)


# PASS --------------------------------------------------------------------


pass <- dplyr::case_when(
  scale == statue ~ "Attention",
  scale == "Statue-Body Movement" ~ "Attention",
  scale == "Statue-Eye Opening" ~ "Attention",
  scale == "Statue-Vocalization" ~ "Attention",
  scale == "Auditory Attention Correct" ~ "Attention",
  scale == "Auditory Attention" ~ "Attention",
  scale == "Auditory Attention Omission Errors" ~ "Attention",
  scale == "Auditory Attention Commission Errors" ~ "Attention",
  scale == "Auditory Attention Inhibitory Errors" ~ "Attention",
  scale == "Response Set Correct" ~ "Attention",
  scale == "Response Set" ~ "Attention",
  scale == "Response Set Omission Errors" ~ "Attention",
  scale == "Response Set Commission Errors" ~ "Attention",
  scale == "Response Set Inhibitory Errors" ~ "Attention",
  scale == "AA vs. RS" ~ "Attention",
  scale == "Clocks" ~ "Planning",
  scale == "Animal Sorting Correct Sorts" ~ "Sequential",
  scale == "Animal Sorting Errors" ~ "Sequential",
  scale == "Animal Sorting Repeated Sort Errors" ~ "Sequential",
  scale == "Animal Sorting Novel Sort Errors" ~ "Sequential",
  scale == "Animal Sorting" ~ "Sequential",
  scale == "Naming Time" ~ "Attention",
  scale == "Naming" ~ "Attention",
  scale == "Naming Errors" ~ "Attention",
  scale == "Naming Self-Corrected Errors" ~ "Attention",
  scale == "Naming Uncorrected Errors" ~ "Attention",
  scale == "Inhibition Time" ~ "Attention",
  scale == "Inhibition" ~ "Attention",
  scale == "Inhibition Errors" ~ "Attention",
  scale == "Inhibition Self-Corrected Errors" ~ "Attention",
  scale == "Inhibition Uncorrected Errors" ~ "Attention",
  scale == "Switching Time" ~ "Attention",
  scale == "Switching" ~ "Attention",
  scale == "Switching Errors" ~ "Attention",
  scale == "Switching Self-Corrected Errors" ~ "Attention",
  scale == "Switching Uncorrected Errors" ~ "Attention",
  scale == "Naming vs. Inhibition" ~ "",
  scale == "Inhibition vs. Switching" ~ "",
  scale == "Inhibition Total Errors" ~ "Attention",
  # Language
  scale == "Body Part Naming" ~ "Simultaneous",
  scale == "Body Part Identification" ~ "Simultaneous",
  scale == "Naming vs Identification" ~ "Simultaneous",
  scale == "Oromotor Sequences" ~ "Sequential",
  scale == "Comprehension of Instructions" ~ "Sequential",
  scale == "Speeded Naming Time" ~ "Attention",
  scale == "Speeded Naming Correct" ~ "Attention",
  scale == "Speeded Naming" ~ "Attention",
  scale == "Speeded Naming Self-Corrected Errors" ~ "Attention",
  scale == "Word Generation-Semantic" ~ "Sequential",
  scale == "Word Generation-Initial Letter" ~ "Sequential",
  scale == "Semantic vs. Initial Letter" ~ "",
  # Memory
  scale == "Sentence Repetition" ~ "Sequential",
  scale == "List Memory and List Memory Delayed" ~ "Verbal",
  scale == "Narrative Memory Free and Cued Recall" ~ "Sequential",
  scale == "Narrative Memory Free Recall" ~ "Sequential",
  scale == "Narrative Memory Recognition" ~ "Sequential",
  scale == "Memory for Designs" ~ "Simultaneous",
  scale == "Memory for Designs Content" ~ "Simultaneous",
  scale == "Memory for Designs Spatial" ~ "Simultaneous",
  scale == "Memory for Designs Delayed" ~ "Simultaneous",
  scale == "Memory for Designs Delayed Content" ~ "Simultaneous",
  scale == "Memory for Designs Delayed Spatial" ~ "Simultaneous",
  scale == "Design Copying General" ~ "Simultaneous",
  scale == "Recall vs Recognition" ~ "",
  # Motor
  scale == "Imitating Hand Positions" ~ "Simultaneous",
  scale == "Imitating Hand Positions-Dominant" ~ "Simultaneous",
  scale == "Imitating Hand Positions-Nondominant" ~ "Simultaneous",
  scale == "Fingertip Tapping Dominant Hand Repetitions" ~ "Sequential",
  scale == "Fingertip Tapping Dominant Hand Sequences" ~ "Sequential",
  scale == "Fingertip Tapping Nondominant Hand Repetitions" ~ "Planning",
  scale == "Fingertip Tapping Nondominant Hand Sequences" ~ "Planning",
  scale == "Fingertip Tapping Dominant Hand" ~ "Planning",
  scale == "Fingertip Tapping Nondominant Hand" ~ "Planning",
  scale == "Fingertip Tapping Repetitions" ~ "Planning",
  scale == "Fingertip Tapping Sequences" ~ "Planning",
  scale == "Dominant vs. Nondominant" ~ "",
  scale == "Repetitions vs. Sequences" ~ "",
  scale == "Visuomotor Precision Time" ~ "Attention",
  scale == "Visuomotor Precision Errors" ~ "Attention",
  scale == "Visuomotor Precision" ~ "Attention",
  scale == "Visuomotor Precision Pencil Lifts" ~ "Attention",
  scale == "Affect Recognition" ~ "Sequential",
  scale == "Affect Recognition Happy Errors" ~ "Sequential",
  scale == "Affect Recognition Sad Errors" ~ "Sequential",
  scale == "Affect Recognition Neutral Errors" ~ "Sequential",
  scale == "Affect Recognition Fear Errors" ~ "Sequential",
  scale == "Affect Recognition Angry Errors" ~ "Sequential",
  scale == "Affect Recognition Disgust Errors" ~ "Sequential",
  scale == "Theory of Mind" ~ "Sequential",
  scale == "Theory of Mind Verbal" ~ "Sequential",
  scale == "Arrows" ~ "Sequential",
  scale == "Design Copying General" ~ "Planning",
  scale == "Design Copying Process" ~ "Planning",
  scale == "Design Copying Process Global" ~ "Planning",
  scale == "Design Copying Process Local" ~ "Planning",
  scale == "Design Copying Process Motor" ~ "Planning",
  scale == "Memory for Faces" ~ "Simultaneous",
  scale == "Memory for Faces Delayed" ~ "Simultaneous",
  scale == "Word List Interference-Repetition" ~ "Sequential",
  scale == "Word List Interference-Recall" ~ "Sequential",
  scale == "Geometric Puzzles" ~ "Simultaneous",
  TRUE ~ NA_character_
)


# Verbal ------------------------------------------------------------------



verbal <- dplyr::case_when(
  scale %in% statue ~ "Verbal",
  scale == "Auditory Attention Correct" ~ "Verbal",
  scale == "Auditory Attention" ~ "Verbal",
  scale == "Auditory Attention Omission Errors" ~ "Verbal",
  scale == "Auditory Attention Commission Errors" ~ "Verbal",
  scale == "Auditory Attention Inhibitory Errors" ~ "Verbal",
  scale == "Response Set Correct" ~ "Verbal",
  scale == "Response Set" ~ "Verbal",
  scale == "Response Set Omission Errors" ~ "Verbal",
  scale == "Response Set Commission Errors" ~ "Verbal",
  scale == "Response Set Inhibitory Errors" ~ "Verbal",
  scale == "AA vs. RS" ~ "Verbal",
  scale == "Sentence Repetition" ~ "Verbal",
  scale == "Clocks" ~ "Nonverbal",
  scale == "List Memory and List Memory Delayed" ~ "Verbal",
  scale == "Narrative Memory Free and Cued Recall" ~ "Verbal",
  scale == "Narrative Memory Free Recall" ~ "Verbal",
  scale == "Narrative Memory Recognition" ~ "Verbal",
  scale == "Recall vs Recognition" ~ "",
  scale == "Memory for Designs" ~ "Nonverbal",
  scale == "Memory for Designs Content" ~ "Nonverbal",
  scale == "Memory for Designs Spatial" ~ "Nonverbal",
  scale == "Memory for Designs Delayed" ~ "Nonverbal",
  scale == "Memory for Designs Delayed Content" ~ "Nonverbal",
  scale == "Memory for Designs Delayed Spatial" ~ "Nonverbal",
  scale == "Visuomotor Precision Time" ~ "Nonverbal",
  scale == "Visuomotor Precision Errors" ~ "Nonverbal",
  scale == "Visuomotor Precision" ~ "Nonverbal",
  scale == "Visuomotor Precision Pencil Lifts" ~ "Nonverbal",
  scale == "Animal Sorting Correct Sorts" ~ "Nonverbal",
  scale == "Animal Sorting Errors" ~ "Nonverbal",
  scale == "Animal Sorting Repeated Sort Errors" ~ "Nonverbal",
  scale == "Animal Sorting Novel Sort Errors" ~ "Nonverbal",
  scale == "Animal Sorting" ~ "Nonverbal",
  scale == "Naming Time" ~ "Verbal",
  scale == "Naming" ~ "Verbal",
  scale == "Naming Errors" ~ "Verbal",
  scale == "Naming Self-Corrected Errors" ~ "Verbal",
  scale == "Naming Uncorrected Errors" ~ "Verbal",
  scale == "Inhibition Time" ~ "Verbal",
  scale == "Inhibition" ~ "Verbal",
  scale == "Inhibition Errors" ~ "Verbal",
  scale == "Inhibition Self-Corrected Errors" ~ "Verbal",
  scale == "Inhibition Uncorrected Errors" ~ "Verbal",
  scale == "Switching Time" ~ "Verbal",
  scale == "Switching" ~ "Verbal",
  scale == "Switching Errors" ~ "Verbal",
  scale == "Switching Self-Corrected Errors" ~ "Verbal",
  scale == "Switching Uncorrected Errors" ~ "Verbal",
  scale == "Naming vs. Inhibition" ~ "",
  scale == "Inhibition vs. Switching" ~ "Verbal",
  scale == "Inhibition Total Errors" ~ "Verbal",
  scale == "Comprehension of Instructions" ~ "Verbal",
  scale == "Speeded Naming Time" ~ "Verbal",
  scale == "Speeded Naming Correct" ~ "Verbal",
  scale == "Speeded Naming" ~ "Verbal",
  scale == "Speeded Naming Self-Corrected Errors" ~ "Verbal",
  scale == "Word Generation-Semantic" ~ "Verbal",
  scale == "Word Generation-Initial Letter" ~ "Verbal",
  scale == "Semantic vs. Initial Letter" ~ "",
  scale == "Fingertip Tapping Dominant Hand Repetitions" ~ "Nonverbal",
  scale == "Fingertip Tapping Dominant Hand Sequences" ~ "Nonverbal",
  scale == "Fingertip Tapping Nondominant Hand Repetitions" ~ "Nonverbal",
  scale == "Fingertip Tapping Nondominant Hand Sequences" ~ "Nonverbal",
  scale == "Fingertip Tapping Dominant Hand" ~ "Nonverbal",
  scale == "Fingertip Tapping Nondominant Hand" ~ "Nonverbal",
  scale == "Fingertip Tapping Repetitions" ~ "Nonverbal",
  scale == "Fingertip Tapping Sequences" ~ "Nonverbal",
  scale == "Dominant vs. Nondominant" ~ "",
  scale == "Repetitions vs. Sequences" ~ "",
  scale == "Affect Recognition" ~ "Verbal",
  scale == "Affect Recognition Happy Errors" ~ "Verbal",
  scale == "Affect Recognition Sad Errors" ~ "Verbal",
  scale == "Affect Recognition Neutral Errors" ~ "Verbal",
  scale == "Affect Recognition Fear Errors" ~ "Verbal",
  scale == "Affect Recognition Angry Errors" ~ "Verbal",
  scale == "Affect Recognition Disgust Errors" ~ "Verbal",
  scale == "Theory of Mind" ~ "Verbal",
  scale == "Theory of Mind Verbal" ~ "Verbal",
  scale == "Arrows" ~ "Nonverbal",
  scale == "Design Copying General" ~ "Nonverbal",
  scale == "Design Copying Process" ~ "Nonverbal",
  scale == "Design Copying Process Global" ~ "Nonverbal",
  scale == "Design Copying Process Local" ~ "Nonverbal",
  scale == "Design Copying Process Motor" ~ "Nonverbal",
  scale == "Memory for Faces" ~ "Nonverbal",
  scale == "Memory for Faces Delayed" ~ "Nonverbal",
  scale == "Word List Interference-Repetition" ~ "Verbal",
  scale == "Word List Interference-Recall" ~ "Verbal",
  scale == "Geometric Puzzles" ~ "Nonverbal",
  TRUE ~ NA_character_
)


# Timed -------------------------------------------------------------------



timed <- dplyr::case_when(
  scale %in% statue ~ "Timed",
  scale == "Auditory Attention Correct" ~ "Timed",
  scale == "Auditory Attention" ~ "Timed",
  scale == "Auditory Attention Omission Errors" ~ "Timed",
  scale == "Auditory Attention Commission Errors" ~ "Timed",
  scale == "Auditory Attention Inhibitory Errors" ~ "Timed",
  scale == "Response Set Correct" ~ "Timed",
  scale == "Response Set" ~ "Timed",
  scale == "Response Set Omission Errors" ~ "Timed",
  scale == "Response Set Commission Errors" ~ "Timed",
  scale == "Response Set Inhibitory Errors" ~ "Timed",
  scale == "AA vs. RS" ~ "Timed",
  scale == "Clocks" ~ "Untimed",
  scale == "List Memory and List Memory Delayed" ~ "Untimed",
  scale == "Narrative Memory Free and Cued Recall" ~ "Untimed",
  scale == "Narrative Memory Free Recall" ~ "Untimed",
  scale == "Narrative Memory Recognition" ~ "Untimed",
  scale == "Recall vs Recognition" ~ "",
  scale == "Visuomotor Precision Time" ~ "Timed",
  scale == "Visuomotor Precision Errors" ~ "Timed",
  scale == "Visuomotor Precision" ~ "Timed",
  scale == "Visuomotor Precision Pencil Lifts" ~ "Timed",
  scale == "Affect Recognition" ~ "Untimed",
  scale == "Affect Recognition Happy Errors" ~ "Untimed",
  scale == "Affect Recognition Sad Errors" ~ "Untimed",
  scale == "Affect Recognition Neutral Errors" ~ "Untimed",
  scale == "Affect Recognition Fear Errors" ~ "Untimed",
  scale == "Affect Recognition Angry Errors" ~ "Untimed",
  scale == "Affect Recognition Disgust Errors" ~ "Untimed",
  scale == "Theory of Mind" ~ "Untimed",
  scale == "Theory of Mind Verbal" ~ "Untimed",
  scale == "Arrows" ~ "Untimed",
  scale == "Animal Sorting Correct Sorts" ~ "Untimed",
  scale == "Animal Sorting Errors" ~ "Untimed",
  scale == "Animal Sorting Repeated Sort Errors" ~ "Untimed",
  scale == "Animal Sorting Novel Sort Errors" ~ "Untimed",
  scale == "Animal Sorting" ~ "Untimed",
  scale == "Naming Time" ~ "Timed",
  scale == "Naming" ~ "Timed",
  scale == "Naming Errors" ~ "Timed",
  scale == "Naming Self-Corrected Errors" ~ "Timed",
  scale == "Naming Uncorrected Errors" ~ "Timed",
  scale == "Inhibition Time" ~ "Timed",
  scale == "Inhibition" ~ "Timed",
  scale == "Inhibition Errors" ~ "Timed",
  scale == "Inhibition Self-Corrected Errors" ~ "Timed",
  scale == "Inhibition Uncorrected Errors" ~ "Timed",
  scale == "Switching Time" ~ "Timed",
  scale == "Switching" ~ "Timed",
  scale == "Switching Errors" ~ "Timed",
  scale == "Switching Self-Corrected Errors" ~ "Timed",
  scale == "Switching Uncorrected Errors" ~ "Timed",
  scale == "Naming vs. Inhibition" ~ "",
  scale == "Inhibition vs. Switching" ~ "",
  scale == "Inhibition Total Errors" ~ "Timed",
  scale == "Body Part Naming" ~ "Untimed",
  scale == "Body Part Identification" ~ "Untimed",
  scale == "Naming vs Identification" ~ "Untimed",
  scale == "Oromotor Sequences" ~ "Untimed",
  scale == "Comprehension of Instructions" ~ "Untimed",
  scale == "Speeded Naming Time" ~ "Timed",
  scale == "Speeded Naming Correct" ~ "Timed",
  scale == "Speeded Naming" ~ "Timed",
  scale == "Speeded Naming Self-Corrected Errors" ~ "Timed",
  scale == "Word Generation-Semantic" ~ "Timed",
  scale == "Word Generation-Initial Letter" ~ "Timed",
  scale == "Semantic vs. Initial Letter" ~ "",
  scale == "Imitating Hand Positions" ~ "Untimed",
  scale == "Imitating Hand Positions-Dominant" ~ "Untimed",
  scale == "Imitating Hand Positions-Nondominant" ~ "Untimed",
  scale == "Fingertip Tapping Dominant Hand Repetitions" ~ "Timed",
  scale == "Fingertip Tapping Dominant Hand Sequences" ~ "Timed",
  scale == "Fingertip Tapping Nondominant Hand Repetitions" ~ "Timed",
  scale == "Fingertip Tapping Nondominant Hand Sequences" ~ "Timed",
  scale == "Fingertip Tapping Dominant Hand" ~ "Timed",
  scale == "Fingertip Tapping Nondominant Hand" ~ "Timed",
  scale == "Fingertip Tapping Repetitions" ~ "Timed",
  scale == "Fingertip Tapping Sequences" ~ "Timed",
  scale == "Dominant vs. Nondominant" ~ "",
  scale == "Repetitions vs. Sequences" ~ "",
  scale == "Imitating Hand Positions" ~ "Untimed",
  scale == "Design Copying" ~ "Untimed",
  scale == "Design Copying Process" ~ "Untimed",
  scale == "Design Copying Process Global" ~ "Untimed",
  scale == "Design Copying Process Local" ~ "Untimed",
  scale == "Design Copying Process Motor" ~ "Untimed",
  scale == "Geometric Puzzles" ~ "Untimed",
  # Memory
  scale == "Memory for Faces" ~ "Untimed",
  scale == "Memory for Faces Delayed" ~ "Untimed",
  scale == "Word List Interference-Repetition" ~ "Untimed",
  scale == "Word List Interference-Recall" ~ "Untimed",
  scale == "Memory for Designs" ~ "Untimed",
  scale == "Memory for Designs Content" ~ "Untimed",
  scale == "Memory for Designs Spatial" ~ "Untimed",
  scale == "Memory for Designs Delayed" ~ "Untimed",
  scale == "Memory for Designs Delayed Content" ~ "Untimed",
  scale == "Memory for Designs Delayed Spatial" ~ "Untimed",
  TRUE ~ NA_character_
)


# Score type --------------------------------------------------------------


score_type <- dplyr::case_when(
  scale == "Animal Sorting Errors" ~ "percentile",
  scale == "Animal Sorting Repeated Sort Errors" ~ "percentile",
  scale == "Animal Sorting Novel Sort Errors" ~ "percentile",
  scale == "Naming Errors" ~ "percentile",
  scale == "Naming Self-Corrected Errors" ~ "percentile",
  scale == "Naming Uncorrected Errors" ~ "percentile",
  scale == "Inhibition Errors" ~ "percentile",
  scale == "Inhibition Self-Corrected Errors" ~ "percentile",
  scale == "Inhibition Uncorrected Errors" ~ "percentile",
  scale == "Switching Errors" ~ "percentile",
  scale == "Switching Self-Corrected Errors" ~ "percentile",
  scale == "Switching Uncorrected Errors" ~ "percentile",
  scale == "Design Copying General" ~ "percentile",
  scale == "Auditory Attention Omission Errors" ~ "percentile",
  scale == "Auditory Attention Commission Errors" ~ "percentile",
  scale == "Auditory Attention Inhibitory Errors" ~ "percentile",
  scale == "Response Set Omission Errors" ~ "percentile",
  scale == "Response Set Commission Errors" ~ "percentile",
  scale == "Response Set Inhibitory Errors" ~ "percentile",
  scale == "Narrative Memory Recognition" ~ "percentile",
  scale == "Fingertip Tapping Dominant Hand Repetitions" ~ "percentile",
  scale == "Fingertip Tapping Dominant Hand Sequences" ~ "percentile",
  scale == "Fingertip Tapping Nondominant Hand Repetitions" ~ "percentile",
  scale == "Fingertip Tapping Nondominant Hand Sequences" ~ "percentile",
  TRUE ~ NA_character_
)


# Description -------------------------------------------------------------



description <- dplyr::case_when(
  # ATT/EX
  scale == "Animal Sorting Correct Sorts" ~ "Concept formation and abstract reasoning correct sorts",
  scale == "Animal Sorting Errors" ~ "Concept formation and abstract reasoning errors",
  scale == "Animal Sorting Novel Sort Errors" ~ "Concept formation and abstract reasoning novel errors",
  scale == "Animal Sorting Repeated Sort Errors" ~ "Concept formation and abstract reasoning repeated errors",
  scale == "Animal Sorting" ~ "Concept formation and abstract reasoning",
  scale == "Arrows" ~ "Visual perception of one-dimensional line orientation",
  scale == "Auditory Attention Commission Errors" ~ "Sustained auditory attention (comissions)",
  scale == "Auditory Attention Correct" ~ "Sustained auditory attention (correct)",
  scale == "Auditory Attention Inhibitory Errors" ~ "Sustained auditory attention (inhibitory errors)",
  scale == "Auditory Attention Omission Errors" ~ "Sustained auditory attention (omissions)",
  scale == "Auditory Attention" ~ "Sustained auditory attention",
  scale == "AA vs. RS" ~ "Sustained auditory attention and inhibition (contrast)",
  scale == "Body Part Identification" ~ "Confrontation naming and name recognition, basic components of expressive and expressive language",
  scale == "Body Part Naming" ~ "Confrontation naming and name recognition, basic components of expressive and expressive language",
  scale == "Clocks" ~ "Planning and organization of an analog clock",
  scale == "Comprehension of Instructions" ~ "The ability to follow multistep instructions",
  scale == "Design Copying General" ~ "Copying and visuomotor integration",
  scale == "Design Copying Process Global" ~ "Copying and visuomotor integration process global",
  scale == "Design Copying Process Local" ~ "Copying and visuomotor integration process local",
  scale == "Design Copying Process Motor" ~ "Copying and visuomotor integration process motor",
  scale == "Design Copying Process" ~ "Copying and visuomotor integration process",
  scale == "Dominant vs. Nondominant" ~ "Dominant vs. Nondominant",
  scale == "Fingertip Tapping Dominant Hand Repetitions" ~ "Finger dexterity and motor speed",
  scale == "Fingertip Tapping Dominant Hand Sequences" ~ "Rapid motor programing",
  scale == "Fingertip Tapping Dominant Hand" ~ "Finger dexterity dominant hand",
  scale == "Fingertip Tapping Nondominant Hand Repetitions" ~ "Finger dexterity and motor speed",
  scale == "Fingertip Tapping Nondominant Hand Sequences" ~ "Rapid motor programing",
  scale == "Fingertip Tapping Nondominant Hand" ~ "Finger dexterity nondominant hand",
  scale == "Fingertip Tapping Repetitions" ~ "Finger dexterity and motor speed",
  scale == "Fingertip Tapping Sequences" ~ "Rapid motor programing",
  scale == "Geometric Puzzles" ~ "Complex abstract geometric puzzles",
  scale == "Imitating Hand Positions-Dominant" ~ "Assess the ability to imitate hand and finger positions",
  scale == "Imitating Hand Positions-Nondominant" ~ "Assess the ability to imitate hand and finger positions",
  scale == "Imitating Hand Positions" ~ "Assess the ability to imitate hand and finger positions",
  scale == "Naming Errors" ~ "Rapid automatic naming (errors)",
  scale == "Naming Self-Corrected Errors" ~ "Rapid automatic naming (self-corrected errors)",
  scale == "Naming Time" ~ "Rapid automatic naming (time)",
  scale == "Naming Uncorrected Errors" ~ "Rapid automatic naming (uncorrected errors)",
  scale == "Naming vs Identification" ~ "Confrontation naming and name recognition, basic components of expressive and expressive language",
  scale == "Naming" ~ "rapid automatic naming",
  scale == "Inhibition Errors" ~ "Inhibition and cognitive control (errors)",
  scale == "Inhibition Self-Corrected Errors" ~ "Inhibition and cognitive control (self-corrected errors)",
  scale == "Inhibition Time" ~ "Inhibition and cognitive control (time)",
  scale == "Inhibition Total Errors" ~ "Response monitoring during inhibition",
  scale == "Inhibition Uncorrected Errors" ~ "Inhibition and cognitive control (uncorrected errors)",
  scale == "Inhibition vs. Switching" ~ "Inhibition vs. Switching",
  scale == "Inhibition" ~ "Inhibition and cognitive control",
  scale == "Response Set Commission Errors" ~ "Sustained auditory attention and inhibition (commissions)",
  scale == "Response Set Correct" ~ "Sustained auditory attention and inhibition",
  scale == "Response Set Inhibitory Errors" ~ "Sustained auditory attention and inhibition (inhibitory errors)",
  scale == "Response Set Omission Errors" ~ "Sustained auditory attention and inhibition (omissions)",
  scale == "Response Set" ~ "Sustained auditory attention and inhibition",
  scale == "List Memory and List Memory Delayed" ~ "Learning and recall of rote information (word list)",
  scale == "Memory for Designs Content" ~ "Immediate memory recall of abstract shape learning (content)",
  scale == "Memory for Designs Delayed Content" ~ "Delayed memory recall of abstract shape learning (content)",
  scale == "Memory for Designs Delayed Spatial" ~ "Delayed memory recall of abstract shape learning (spatial)",
  scale == "Memory for Designs Delayed" ~ "Delayed memory recall of abstract shape learning",
  scale == "Memory for Designs Spatial" ~ "Immediate memory recall of abstract shape learning (spatial)",
  scale == "Memory for Designs" ~ "Immediate memory recall of abstract shape learning",
  scale == "Memory for Faces Delayed" ~ "Delayed recall/recognition of children's faces",
  scale == "Memory for Faces" ~ "Memory for children's faces",
  scale == "Narrative Memory Free and Cued Recall" ~ "Long-term memory recall of story details with cues",
  scale == "Narrative Memory Free Recall" ~ "Long-term memory recall of story details",
  scale == "Narrative Memory Recognition" ~ "Long-term memory recognition of story details",
  scale == "Oromotor Sequences" ~ "Oromotor coordination in repeating articulatory sequences",
  scale == "Recall vs Recognition" ~ "Memory recall vs recognition",
  scale == "Repetitions vs. Sequences" ~ "Repetitions vs. Sequences",
  scale == "Semantic vs. Initial Letter" ~ "Semantic vs phonemic word fluency",
  scale == "Sentence Repetition" ~ "The ability to repeat sentences of increasing complexity and length",
  scale == "Speeded Naming Correct" ~ "Naming correct",
  scale == "Speeded Naming Self-Corrected Errors" ~ "Response monitoring during naming",
  scale == "Speeded Naming Time" ~ "Naming facility for familiar/overlearned information",
  scale == "Speeded Naming" ~ "Rapid access to and production of names of colors, shapes, sizes, letters, or numbers",
  scale == "Statue-Body Movement" ~ "Motor persistence and inhibition (movement)",
  scale == "Statue-Eye Opening" ~ "Motor persistence and inhibition (eye opening)",
  scale == "Statue-Vocalization" ~ "Motor persistence and inhibition (vocalization)",
  scale == statue ~ "Motor persistence and inhibition",
  scale == "Switching Errors" ~ "Set-shifting and cognitive flexibility (errors)",
  scale == "Switching Self-Corrected Errors" ~ "Set-shifting and cognitive flexibility (self-corrected errors)",
  scale == "Switching Time" ~ "Set-shifting and cognitive flexibility (time)",
  scale == "Switching Uncorrected Errors" ~ "Set-shifting and cognitive flexibility (uncorrected errors)",
  scale == "Switching" ~ "Set-shifting and cognitive flexibility",
  scale == "Theory of Mind" ~ "The ability to understand mental functions and another’s point of view",
  scale == "Theory of Mind Verbal" ~ "Belief, intention, deception, emotion, imagination/pretending, imitation, and the understanding of other’s thoughts, ideas, and feelings, as well as comprehension of abstract meanings in figurative language",
  scale == "Visuomotor Precision Errors" ~ "Graphomotor speed and accuracy (errors)",
  scale == "Visuomotor Precision Pencil Lifts" ~ "Graphomotor speed and accuracy (pencil control)",
  scale == "Visuomotor Precision Time" ~ "Graphomotor speed and accuracy (time)",
  scale == "Visuomotor Precision" ~ "Graphomotor speed and accuracy",
  scale == "Affect Recognition" ~ "The ability to recognize affect from photographs of children's faces in four different tasks",
  scale == "Word Generation-Initial Letter" ~ "Ability to generate words in 60-seconds given a phonemic (letter) cue",
  scale == "Word Generation-Semantic" ~ "Ability to generate words within specific semantically-related categories in 60-seconds",
  scale == "Word List Interference-Recall" ~ "Verbal associative learning (word pairs) recall",
  scale == "Word List Interference-Repetition" ~ "Verbal associative learning (word pairs) repetition",
  TRUE ~ NA_character_
)

nepsy2 <- data.frame(
  test = rep("nepsy2", length(scale)),
  scale = scale,
  domain = domain,
  subdomain = subdomain,
  narrow = narrow,
  pass = pass,
  verbal = verbal,
  timed = timed,
  score_type = score_type,
  description = description
)
