quarto::quarto_render(
  input = "{{< var patient >}}.qmd",
  execute_params = list(
    patient = "{{< var patient >}}",
    first_name = "{{< var patient >}}",
    last_name = "Smalls",
    dob = "10/04/1999",
    doe = "2023-01-01",
    doe2 = "2023-01-02",
    doe3 = NULL,
    date_of_report = "",
    sex = "female",
    sex_cap = "Female",
    age = 12,
    education = 15,
    handedness = "right",
    referral = "Dr. Dre",
    observer = "Mrs. Wallace",
    observer_relation = "mother",
    he_she = "she",
    he_she_cap = "She",
    his_her = "her",
    his_her_cap = "Her",
    him_her = "her",
    him_her_cap = "Her",
    dx1 = "attention-deficit/hyperactivity disorder (ADHD)",
    dx2 = "anxiety",
    dx3 = "depression"
  ),
  output_file = "{{< var patient >}}.pdf"
)
